In [3]:
import requests

url = 'http://openapi.seoul.go.kr:8088/4768796e76646f6738376c4d4a6153/json/SebcCollegeInfoKor/1/100/'
r = requests.get(url)

In [6]:
print(r.content)

b'{"SebcCollegeInfoKor":{"list_total_count":64,"RESULT":{"CODE":"INFO-000","MESSAGE":"\xec\xa0\x95\xec\x83\x81 \xec\xb2\x98\xeb\xa6\xac\xeb\x90\x98\xec\x97\x88\xec\x8a\xb5\xeb\x8b\x88\xeb\x8b\xa4"},"row":[{"MAIN_KEY":"BE_LiST23-0034","YEAR":"2013","CATE1_NAME":"\xec\x9d\xbc\xeb\xb0\x98\xeb\x8c\x80\xed\x95\x99","NAME_KOR":"\xec\x84\x9c\xec\x9a\xb8\xec\x8b\x9c\xeb\xa6\xbd\xeb\x8c\x80\xed\x95\x99\xea\xb5\x90","BRANCH":"\xeb\xb3\xb8\xea\xb5\x90","STATE":"\xea\xb8\xb0\xec\xa1\xb4","TYPE":"\xea\xb3\xb5\xeb\xa6\xbd","POSTCODE":"","ADD_KOR":"\xec\x84\x9c\xec\x9a\xb8 \xeb\x8f\x99\xeb\x8c\x80\xeb\xac\xb8\xea\xb5\xac \xec\x84\x9c\xec\x9a\xb8\xec\x8b\x9c\xeb\xa6\xbd\xeb\x8c\x80\xeb\xa1\x9c 163 (\xec\xa0\x84\xeb\x86\x8d\xeb\x8f\x99 90\xeb\xb2\x88\xec\xa7\x80) ","ADD_KOR_ROAD":"","H_KOR_CITY":"\xec\x84\x9c\xec\x9a\xb8\xed\x8a\xb9\xeb\xb3\x84\xec\x8b\x9c","H_KOR_GU":"\xeb\x8f\x99\xeb\x8c\x80\xeb\xac\xb8\xea\xb5\xac","H_KOR_DONG":"\xed\x9c\x98\xea\xb2\xbd2\xeb\x8f\x99","TEL":"02-6490-6114","FAX":"02-2210-5576","HP":"http://www.uos.ac.kr"},{"MAIN_KEY":"BE_LiST23-0035","YEAR":"2013","CATE1_NAME":"\xec\xa0\x84\xeb\xac\xb8\xeb\x8c\x80\xed\x95\x99(3\xeb\x85\x84\xec\xa0\x9c)","NAME_KOR":"\xec\x84\x9c\xec\x9a\xb8\xec\x97\xac\xec\x9e\x90\xea\xb0\x84\xed\x98\xb8\xeb\x8c\x80\xed\x95\x99\xea\xb5\x90","BRANCH":"\xeb\xb3\xb8\xea\xb5\x90","STATE":"\xea\xb8\xb0\xec\xa1\xb4","TYPE":"\xec\x82\xac\xeb\xa6\xbd","POSTCODE":"","ADD_KOR":"\xec\x84\x9c\xec\x9a\xb8 \xec\x84\x9c\xeb\x8c\x80\xeb\xac\xb8\xea\xb5\xac \xed\x99\x8d\xec\xa0\x9c3\xeb\x8f\x99 \xec\x84\x9c\xec\x9a\xb8\xec\x97\xac\xec\x9e\x90\xea\xb0\x84\xed\x98\xb8\xeb\x8c\x80\xed\x95\x99","ADD_KOR_ROAD":"","H_KOR_CITY":"\xec\x84\x9c\xec\x9a\xb8\xed\x8a\xb9\xeb\xb3\x84\xec\x8b\x9c","H_KOR_GU":"\xec\x84\x9c\xeb\x8c\x80\xeb\xac\xb8\xea\xb5\xac","H_KOR_DONG":"\xed\x99\x8d\xec\xa0\x9c2\xeb\x8f\x99","TEL":"02-2287-1700","FAX":"02-395-8018","HP":"http://www.snjc.ac.kr"},{"MAIN_KEY":"BE_LiST23-0036","YEAR":"2013","CATE1_NAME":"\xec\x9d\xbc\xeb\xb0\x98\xeb\x8c\x80\xed\x95\x99","NAME_KOR":"\xec\x84\x9c\xec\x9a\xb8\xec\x97\xac\xec\x9e\x90\xeb\x8c\x80\xed\x95\x99\xea\xb5\x90","BRANCH":"\xeb\xb3\xb8\xea\xb5\x90","STATE":"\xea\xb8\xb0\xec\xa1\xb4","TYPE":"\xec\x82\xac\xeb\xa6\xbd","POSTCODE":"","ADD_KOR":"\xec\x84\x9c\xec\x9a\xb8\xed\x8a\xb9\xeb\xb3\x84\xec\x8b\x9c \xeb\x85\xb8\xec\x9b\x90\xea\xb5\xac \xed\x99\x94\xeb\x9e\x91\xeb\xa1\x9c 621 \xec\x84\x9c\xec\x9a\xb8\xec\x97\xac\xec\x9e\x90\xeb\x8c\x80\xed\x95\x99\xea\xb5\x90","ADD_KOR_ROAD":"","H_KOR_CITY":"\xec\x84\x9c\xec\x9a\xb8\xed\x8a\xb9\xeb\xb3\x84\xec\x8b\x9c","H_KOR_GU":"\xeb\x85\xb8\xec\x9b\x90\xea\xb5\xac","H_KOR_DONG":"\xea\xb3\xb5\xeb\xa6\x892\xeb\x8f\x99","TEL":"02-970-5114","FAX":"02-978-7931","HP":"http://www.swu.ac.kr"},{"MAIN_KEY":"BE_LiST23-0037","YEAR":"2013","CATE1_NAME":"\xec\xa0\x84\xeb\xac\xb8\xeb\x8c\x80\xed\x95\x99(2\xeb\x85\x84\xec\xa0\x9c)","NAME_KOR":"\xec\x84\x9c\xec\x9d\xbc\xeb\x8c\x80\xed\x95\x99\xea\xb5\x90","BRANCH":"\xeb\xb3\xb8\xea\xb5\x90","STATE":"\xed\x95\x99\xea\xb5\x90\xeb\xaa\x85 \xeb\xb3\x80\xea\xb2\xbd","TYPE":"\xec\x82\xac\xeb\xa6\xbd","POSTCODE":"","ADD_KOR":"\xec\x84\x9c\xec\x9a\xb8 \xec\xa4\x91\xeb\x9e\x91\xea\xb5\xac \xec\x84\x9c\xec\x9d\xbc\xeb\x8c\x80\xed\x95\x99\xea\xb8\xb8 22(\xeb\xa9\xb4\xeb\xaa\xa9\xeb\x8f\x99 49-3) \xec\x84\x9c\xec\x9d\xbc\xeb\x8c\x80\xed\x95\x99\xea\xb5\x90","ADD_KOR_ROAD":"","H_KOR_CITY":"\xec\x84\x9c\xec\x9a\xb8\xed\x8a\xb9\xeb\xb3\x84\xec\x8b\x9c","H_KOR_GU":"\xec\xa4\x91\xeb\x9e\x91\xea\xb5\xac","H_KOR_DONG":"\xeb\xa9\xb4\xeb\xaa\xa9\xec\xa0\x9c3.8\xeb\x8f\x99","TEL":"02-490-7300","FAX":"02-493-2576","HP":"http://www.seoil.ac.kr"},{"MAIN_KEY":"BE_LiST23-0038","YEAR":"2013","CATE1_NAME":"\xec\x9d\xbc\xeb\xb0\x98\xeb\x8c\x80\xed\x95\x99","NAME_KOR":"\xec\x84\xb1\xea\xb3\xb5\xed\x9a\x8c\xeb\x8c\x80\xed\x95\x99\xea\xb5\x90","BRANCH":"\xeb\xb3\xb8\xea\xb5\x90","STATE":"\xea\xb8\xb0\xec\xa1\xb4","TYPE":"\xec\x82\xac\xeb\xa6\xbd","POSTCODE":"","ADD_KOR":"\xec\x84\x9c\xec\x9a\xb8 \xea\xb5\xac\xeb\xa1\x9c\xea\xb5\xac \xed\x95\xad\xeb\x8f\x99 \xec\x84\xb1\xea\xb3\xb5\xed\x9a\x8c\xeb\x8c\x80\xed\x95\x99\xea\xb5\x90","ADD_KOR_ROAD":"","H_KOR_CITY":"\xec\x84\x9c\xec\x9a\xb8\xed\x8a\xb9\xeb\xb3\x84\xec\x8b\x9c","H_KOR_GU":"\xea\xb5\xac\xeb\xa1\x9c\xea\xb5\xac","H_KOR_DONG":"\xec\x98\xa4\xeb\xa5\x982\xeb\x8f\x99","TEL":"02-2610-4142","FAX":"02-2610-4248","HP":"http://www.skhu.ac.kr"},{"MAIN_KEY":"BE_LiST23-0039","YEAR":"2013","CATE1_NAME":"\xec\x9d\xbc\xeb\xb0\x98\xeb\x8c\x80\xed\x95\x99","NAME_KOR":"\xec\x84\xb1\xea\xb7\xa0\xea\xb4\x80\xeb\x8c\x80\xed\x95\x99\xea\xb5\x90","BRANCH":"\xeb\xb3\xb8\xea\xb5\x90","STATE":"\xea\xb8\xb0\xec\xa1\xb4","TYPE":"\xec\x82\xac\xeb\xa6\xbd","POSTCODE":"","ADD_KOR":"\xec\x84\x9c\xec\x9a\xb8 \xec\xa2\x85\xeb\xa1\x9c\xea\xb5\xac \xeb\xaa\x85\xeb\xa5\x9c\xeb\x8f\x993\xea\xb0\x80 \xec\x84\xb1\xea\xb7\xa0\xea\xb4\x80\xeb\x8c\x80\xed\x95\x99\xea\xb5\x90","ADD_KOR_ROAD":"","H_KOR_CITY":"\xec\x84\x9c\xec\x9a\xb8\xed\x8a\xb9\xeb\xb3\x84\xec\x8b\x9c","H_KOR_GU":"\xec\xa2\x85\xeb\xa1\x9c\xea\xb5\xac","H_KOR_DONG":"\xec\xa2\x85\xeb\xa1\x9c1.2.3.4\xea\xb0\x80\xeb\x8f\x99","TEL":"02-760-0114","FAX":"","HP":"http://www.skku.edu"},{"MAIN_KEY":"BE_LiST23-0040","YEAR":"2013","CATE1_NAME":"\xec\x9d\xbc\xeb\xb0\x98\xeb\x8c\x80\xed\x95\x99","NAME_KOR":"\xec\x84\xb1\xec\x8b\xa0\xec\x97\xac\xec\x9e\x90\xeb\x8c\x80\xed\x95\x99\xea\xb5\x90","BRANCH":"\xeb\xb3\xb8\xea\xb5\x90","STATE":"\xea\xb8\xb0\xec\xa1\xb4","TYPE":"\xec\x82\xac\xeb\xa6\xbd","POSTCODE":"","ADD_KOR":"\xec\x84\x9c\xec\x9a\xb8 \xec\x84\xb1\xeb\xb6\x81\xea\xb5\xac \xeb\x8f\x99\xec\x84\xa0\xeb\x8f\x993\xea\xb0\x80 \xec\x84\xb1\xec\x8b\xa0\xec\x97\xac\xec\x9e\x90\xeb\x8c\x80\xed\x95\x99\xea\xb5\x90","ADD_KOR_ROAD":"","H_KOR_CITY":"\xec\x84\x9c\xec\x9a\xb8\xed\x8a\xb9\xeb\xb3\x84\xec\x8b\x9c","H_KOR_GU":"\xec\x84\xb1\xeb\xb6\x81\xea\xb5\xac","H_KOR_DONG":"\xeb\x8f\x99\xec\x84\xa0\xeb\x8f\x99","TEL":"02-920-7114","FAX":"02-920-2018","HP":"http://www.sungshin.ac.kr"},{"MAIN_KEY":"BE_LiST23-0041","YEAR":"2013","CATE1_NAME":"\xec\x9d\xbc\xeb\xb0\x98\xeb\x8c\x80\xed\x95\x99","NAME_KOR":"\xec\x84\xb8\xec\xa2\x85\xeb\x8c\x80\xed\x95\x99\xea\xb5\x90","BRANCH":"\xeb\xb3\xb8\xea\xb5\x90","STATE":"\xea\xb8\xb0\xec\xa1\xb4","TYPE":"\xec\x82\xac\xeb\xa6\xbd","POSTCODE":"","ADD_KOR":"\xec\x84\x9c\xec\x9a\xb8 \xea\xb4\x91\xec\xa7\x84\xea\xb5\xac \xea\xb5\xb0\xec\x9e\x90\xeb\x8f\x99 \xec\x84\xb8\xec\xa2\x85\xeb\x8c\x80\xed\x95\x99\xea\xb5\x90","ADD_KOR_ROAD":"","H_KOR_CITY":"\xec\x84\x9c\xec\x9a\xb8\xed\x8a\xb9\xeb\xb3\x84\xec\x8b\x9c","H_KOR_GU":"\xea\xb4\x91\xec\xa7\x84\xea\xb5\xac","H_KOR_DONG":"\xea\xb5\xb0\xec\x9e\x90\xeb\x8f\x99","TEL":"02-3408-3114","FAX":"02-3408-3906","HP":"http://www.sejong.ac.kr"},{"MAIN_KEY":"BE_LiST23-0042","YEAR":"2013","CATE1_NAME":"\xec\x9d\xbc\xeb\xb0\x98\xeb\x8c\x80\xed\x95\x99","NAME_KOR":"\xec\x88\x99\xeb\xaa\x85\xec\x97\xac\xec\x9e\x90\xeb\x8c\x80\xed\x95\x99\xea\xb5\x90","BRANCH":"\xeb\xb3\xb8\xea\xb5\x90","STATE":"\xea\xb8\xb0\xec\xa1\xb4","TYPE":"\xec\x82\xac\xeb\xa6\xbd","POSTCODE":"","ADD_KOR":"\xec\x84\x9c\xec\x9a\xb8 \xec\x9a\xa9\xec\x82\xb0\xea\xb5\xac \xec\xb2\xad\xed\x8c\x8c\xeb\xa1\x9c47\xea\xb8\xb8 100 \xec\x88\x99\xeb\xaa\x85\xec\x97\xac\xec\x9e\x90\xeb\x8c\x80\xed\x95\x99\xea\xb5\x90","ADD_KOR_ROAD":"","H_KOR_CITY":"\xec\x84\x9c\xec\x9a\xb8\xed\x8a\xb9\xeb\xb3\x84\xec\x8b\x9c","H_KOR_GU":"\xec\x9a\xa9\xec\x82\xb0\xea\xb5\xac","H_KOR_DONG":"\xec\xb2\xad\xed\x8c\x8c\xeb\x8f\x99","TEL":"","FAX":"","HP":"http://www.sookmyung.ac.kr/"},{"MAIN_KEY":"BE_LiST23-0043","YEAR":"2013","CATE1_NAME":"\xec\x9d\xbc\xeb\xb0\x98\xeb\x8c\x80\xed\x95\x99","NAME_KOR":"\xec\x88\xad\xec\x8b\xa4\xeb\x8c\x80\xed\x95\x99\xea\xb5\x90","BRANCH":"\xeb\xb3\xb8\xea\xb5\x90","STATE":"\xea\xb8\xb0\xec\xa1\xb4","TYPE":"\xec\x82\xac\xeb\xa6\xbd","POSTCODE":"","ADD_KOR":"\xec\x84\x9c\xec\x9a\xb8 \xeb\x8f\x99\xec\x9e\x91\xea\xb5\xac \xec\x83\x81\xeb\x8f\x84\xeb\x8f\x99 511 \xec\x88\xad\xec\x8b\xa4\xeb\x8c\x80\xed\x95\x99\xea\xb5\x90","ADD_KOR_ROAD":"","H_KOR_CITY":"\xec\x84\x9c\xec\x9a\xb8\xed\x8a\xb9\xeb\xb3\x84\xec\x8b\x9c","H_KOR_GU":"\xeb\x8f\x99\xec\x9e\x91\xea\xb5\xac","H_KOR_DONG":"\xec\x83\x81\xeb\x8f\x841\xeb\x8f\x99","TEL":"02-820-0114","FAX":"","HP":"http://www.ssu.ac.kr"},{"MAIN_KEY":"BE_LiST23-0044","YEAR":"2013","CATE1_NAME":"\xec\xa0\x84\xeb\xac\xb8\xeb\x8c\x80\xed\x95\x99(2\xeb\x85\x84\xec\xa0\x9c)","NAME_KOR":"\xec\x88\xad\xec\x9d\x98\xec\x97\xac\xec\x9e\x90\xeb\x8c\x80\xed\x95\x99\xea\xb5\x90","BRANCH":"\xeb\xb3\xb8\xea\xb5\x90","STATE":"\xea\xb8\xb0\xec\xa1\xb4","TYPE":"\xec\x82\xac\xeb\xa6\xbd","POSTCODE":"","ADD_KOR":"\xec\x84\x9c\xec\x9a\xb8\xed\x8a\xb9\xeb\xb3\x84\xec\x8b\x9c \xec\xa4\x91\xea\xb5\xac \xec\x86\x8c\xed\x8c\x8c\xeb\xa1\x9c2\xea\xb8\xb8 10(\xec\x98\x88\xec\x9e\xa5\xeb\x8f\x99)","ADD_KOR_ROAD":"","H_KOR_CITY":"\xec\x84\x9c\xec\x9a\xb8\xed\x8a\xb9\xeb\xb3\x84\xec\x8b\x9c","H_KOR_GU":"\xec\xa4\x91\xea\xb5\xac","H_KOR_DONG":"\xed\x95\x84\xeb\x8f\x99","TEL":"02-3708-9000","FAX":"02-773-2625","HP":"http://www.sewc.ac.kr"},{"MAIN_KEY":"BE_LiST23-0045","YEAR":"2013","CATE1_NAME":"\xec\x9d\xbc\xeb\xb0\x98\xeb\x8c\x80\xed\x95\x99","NAME_KOR":"\xec\x97\xb0\xec\x84\xb8\xeb\x8c\x80\xed\x95\x99\xea\xb5\x90","BRANCH":"\xeb\xb3\xb8\xea\xb5\x90","STATE":"\xea\xb8\xb0\xec\xa1\xb4","TYPE":"\xec\x82\xac\xeb\xa6\xbd","POSTCODE":"","ADD_KOR":"\xec\x84\x9c\xec\x9a\xb8 \xec\x84\x9c\xeb\x8c\x80\xeb\xac\xb8\xea\xb5\xac \xec\x8b\xa0\xec\xb4\x8c\xeb\x8f\x99 \xec\x97\xb0\xec\x84\xb8\xeb\x8c\x80\xed\x95\x99\xea\xb5\x90","ADD_KOR_ROAD":"","H_KOR_CITY":"\xec\x84\x9c\xec\x9a\xb8\xed\x8a\xb9\xeb\xb3\x84\xec\x8b\x9c","H_KOR_GU":"\xec\x84\x9c\xeb\x8c\x80\xeb\xac\xb8\xea\xb5\xac","H_KOR_DONG":"\xec\x8b\xa0\xec\xb4\x8c\xeb\x8f\x99","TEL":"02-2123-2114","FAX":"02-392-0618","HP":"http://www.yonsei.ac.kr"},{"MAIN_KEY":"BE_LiST23-0046","YEAR":"2013","CATE1_NAME":"\xec\x9d\xbc\xeb\xb0\x98\xeb\x8c\x80\xed\x95\x99","NAME_KOR":"\xec\x9d\xb4\xed\x99\x94\xec\x97\xac\xec\x9e\x90\xeb\x8c\x80\xed\x95\x99\xea\xb5\x90","BRANCH":"\xeb\xb3\xb8\xea\xb5\x90","STATE":"\xea\xb8\xb0\xec\xa1\xb4","TYPE":"\xec\x82\xac\xeb\xa6\xbd","POSTCODE":"","ADD_KOR":"\xec\x84\x9c\xec\x9a\xb8 \xec\x84\x9c\xeb\x8c\x80\xeb\xac\xb8\xea\xb5\xac \xeb\x8c\x80\xed\x98\x84\xeb\x8f\x99 11-1 \xec\x9d\xb4\xed\x99\x94\xec\x97\xac\xec\x9e\x90\xeb\x8c\x80\xed\x95\x99\xea\xb5\x90","ADD_KOR_ROAD":"","H_KOR_CITY":"\xec\x84\x9c\xec\x9a\xb8\xed\x8a\xb9\xeb\xb3\x84\xec\x8b\x9c","H_KOR_GU":"\xec\x84\x9c\xeb\x8c\x80\xeb\xac\xb8\xea\xb5\xac","H_KOR_DONG":"\xec\x8b\xa0\xec\xb4\x8c\xeb\x8f\x99","TEL":"02-3277-2114","FAX":"02-393-5903","HP":"http://www.ewha.ac.kr"},{"MAIN_KEY":"BE_LiST23-0047","YEAR":"2013","CATE1_NAME":"\xec\xa0\x84\xeb\xac\xb8\xeb\x8c\x80\xed\x95\x99(2\xeb\x85\x84\xec\xa0\x9c)","NAME_KOR":"\xec\x9d\xb8\xeb\x8d\x95\xeb\x8c\x80\xed\x95\x99\xea\xb5\x90","BRANCH":"\xeb\xb3\xb8\xea\xb5\x90","STATE":"\xea\xb8\xb0\xec\xa1\xb4","TYPE":"\xec\x82\xac\xeb\xa6\xbd","POSTCODE":"","ADD_KOR":"\xec\x84\x9c\xec\x9a\xb8 \xeb\x85\xb8\xec\x9b\x90\xea\xb5\xac \xec\xb4\x88\xec\x95\x88\xec\x82\xb0\xeb\xa1\x9c 12","ADD_KOR_ROAD":"","H_KOR_CITY":"\xec\x84\x9c\xec\x9a\xb8\xed\x8a\xb9\xeb\xb3\x84\xec\x8b\x9c","H_KOR_GU":"\xeb\x85\xb8\xec\x9b\x90\xea\xb5\xac","H_KOR_DONG":"\xec\x9b\x94\xea\xb3\x842\xeb\x8f\x99","TEL":"02-950-7000","FAX":"02-906-5340","HP":"http://www.induk.ac.kr"},{"MAIN_KEY":"BE_LiST23-0048","YEAR":"2013","CATE1_NAME":"\xec\x9d\xbc\xeb\xb0\x98\xeb\x8c\x80\xed\x95\x99","NAME_KOR":"\xec\x9e\xa5\xeb\xa1\x9c\xed\x9a\x8c\xec\x8b\xa0\xed\x95\x99\xeb\x8c\x80\xed\x95\x99\xea\xb5\x90","BRANCH":"\xeb\xb3\xb8\xea\xb5\x90","STATE":"\xea\xb8\xb0\xec\xa1\xb4","TYPE":"\xec\x82\xac\xeb\xa6\xbd","POSTCODE":"","ADD_KOR":"\xec\x84\x9c\xec\x9a\xb8 \xea\xb4\x91\xec\xa7\x84\xea\xb5\xac \xea\xb4\x91\xec\x9e\xa5\xeb\xa1\x9c 5\xea\xb8\xb8 25-1(\xea\xb4\x91\xec\x9e\xa5\xeb\x8f\x99) \xec\x9e\xa5\xeb\xa1\x9c\xed\x9a\x8c\xec\x8b\xa0\xed\x95\x99\xeb\x8c\x80\xed\x95\x99\xea\xb5\x90","ADD_KOR_ROAD":"","H_KOR_CITY":"\xec\x84\x9c\xec\x9a\xb8\xed\x8a\xb9\xeb\xb3\x84\xec\x8b\x9c","H_KOR_GU":"\xea\xb4\x91\xec\xa7\x84\xea\xb5\xac","H_KOR_DONG":"\xea\xb4\x91\xec\x9e\xa5\xeb\x8f\x99","TEL":"02-450-0700","FAX":"","HP":"http://www.pcts.ac.kr"},{"MAIN_KEY":"BE_LiST23-0049","YEAR":"2013","CATE1_NAME":"\xec\xa0\x84\xeb\xac\xb8\xeb\x8c\x80\xed\x95\x99(3\xeb\x85\x84\xec\xa0\x9c)","NAME_KOR":"\xec\xa0\x81\xec\x8b\xad\xec\x9e\x90\xea\xb0\x84\xed\x98\xb8\xeb\x8c\x80\xed\x95\x99","BRANCH":"\xeb\xb3\xb8\xea\xb5\x90","STATE":"\xed\x8f\x90\xea\xb5\x90","TYPE":"\xec\x82\xac\xeb\xa6\xbd","POSTCODE":"","ADD_KOR":"\xec\x84\x9c\xec\x9a\xb8 \xec\xa2\x85\xeb\xa1\x9c\xea\xb5\xac \xea\xb2\xbd\xea\xb5\x90\xec\x9e\xa5\xea\xb8\xb88","ADD_KOR_ROAD":"","H_KOR_CITY":"\xec\x84\x9c\xec\x9a\xb8\xed\x8a\xb9\xeb\xb3\x84\xec\x8b\x9c","H_KOR_GU":"\xec\xa2\x85\xeb\xa1\x9c\xea\xb5\xac","H_KOR_DONG":"\xea\xb5\x90\xeb\x82\xa8\xeb\x8f\x99","TEL":"02-3700-3600","FAX":"02-3700-3400","HP":"http://redcross.cau.ac.kr"},{"MAIN_KEY":"BE_LiST23-0050","YEAR":"2013","CATE1_NAME":"\xec\x9d\xbc\xeb\xb0\x98\xeb\x8c\x80\xed\x95\x99","NAME_KOR":"\xec\xa4\x91\xec\x95\x99\xeb\x8c\x80\xed\x95\x99\xea\xb5\x90 \xec\x84\x9c\xec\x9a\xb8\xec\xba\xa0\xed\x8d\xbc\xec\x8a\xa4","BRANCH":"\xeb\xb3\xb8\xea\xb5\x90","STATE":"\xea\xb8\xb0\xec\xa1\xb4","TYPE":"\xec\x82\xac\xeb\xa6\xbd","POSTCODE":"","ADD_KOR":"\xec\x84\x9c\xec\x9a\xb8 \xeb\x8f\x99\xec\x9e\x91\xea\xb5\xac \xed\x9d\x91\xec\x84\x9d\xeb\xa1\x9c 84","ADD_KOR_ROAD":"","H_KOR_CITY":"\xec\x84\x9c\xec\x9a\xb8\xed\x8a\xb9\xeb\xb3\x84\xec\x8b\x9c","H_KOR_GU":"\xeb\x8f\x99\xec\x9e\x91\xea\xb5\xac","H_KOR_DONG":"\xed\x9d\x91\xec\x84\x9d\xeb\x8f\x99","TEL":"02-820-5114","FAX":"","HP":"http://www.cau.ac.kr"},{"MAIN_KEY":"BE_LiST23-0051","YEAR":"2013","CATE1_NAME":"\xec\x9d\xbc\xeb\xb0\x98\xeb\x8c\x80\xed\x95\x99","NAME_KOR":"\xec\xb4\x9d\xec\x8b\xa0\xeb\x8c\x80\xed\x95\x99\xea\xb5\x90","BRANCH":"\xeb\xb3\xb8\xea\xb5\x90","STATE":"\xea\xb8\xb0\xec\xa1\xb4","TYPE":"\xec\x82\xac\xeb\xa6\xbd","POSTCODE":"","ADD_KOR":"\xec\x84\x9c\xec\x9a\xb8 \xeb\x8f\x99\xec\x9e\x91\xea\xb5\xac \xec\x82\xac\xeb\x8b\xb9\xeb\x8f\x99 \xec\x82\xb031-3","ADD_KOR_ROAD":"","H_KOR_CITY":"\xec\x84\x9c\xec\x9a\xb8\xed\x8a\xb9\xeb\xb3\x84\xec\x8b\x9c","H_KOR_GU":"\xeb\x8f\x99\xec\x9e\x91\xea\xb5\xac","H_KOR_DONG":"\xec\x82\xac\xeb\x8b\xb93\xeb\x8f\x99","TEL":"02-3479-0200","FAX":"02-536-2602","HP":"http://www.chongshin.ac.kr"},{"MAIN_KEY":"BE_LiST23-0052","YEAR":"2013","CATE1_NAME":"\xec\x9d\xbc\xeb\xb0\x98\xeb\x8c\x80\xed\x95\x99","NAME_KOR":"\xec\xb6\x94\xea\xb3\x84\xec\x98\x88\xec\x88\xa0\xeb\x8c\x80\xed\x95\x99\xea\xb5\x90","BRANCH":"\xeb\xb3\xb8\xea\xb5\x90","STATE":"\xea\xb8\xb0\xec\xa1\xb4","TYPE":"\xec\x82\xac\xeb\xa6\xbd","POSTCODE":"","ADD_KOR":"\xec\x84\x9c\xec\x9a\xb8 \xec\x84\x9c\xeb\x8c\x80\xeb\xac\xb8\xea\xb5\xac \xeb\xb6\x81\xec\x95\x84\xed\x98\x84\xeb\x8f\x99 190-1 \xec\xb6\x94\xea\xb3\x84\xec\x98\x88\xec\x88\xa0\xeb\x8c\x80\xed\x95\x99\xea\xb5\x90","ADD_KOR_ROAD":"","H_KOR_CITY":"\xec\x84\x9c\xec\x9a\xb8\xed\x8a\xb9\xeb\xb3\x84\xec\x8b\x9c","H_KOR_GU":"\xec\x84\x9c\xeb\x8c\x80\xeb\xac\xb8\xea\xb5\xac","H_KOR_DONG":"\xec\xb6\xa9\xed\x98\x84\xeb\x8f\x99","TEL":"02-362-5700","FAX":"02-392-1777","HP":"http://www.chugye.ac.kr"},{"MAIN_KEY":"BE_LiST23-0053","YEAR":"2013","CATE1_NAME":"\xeb\xb0\xa9\xec\x86\xa1\xed\x86\xb5\xec\x8b\xa0\xeb\x8c\x80\xed\x95\x99","NAME_KOR":"\xed\x95\x9c\xea\xb5\xad\xeb\xb0\xa9\xec\x86\xa1\xed\x86\xb5\xec\x8b\xa0\xeb\x8c\x80\xed\x95\x99\xea\xb5\x90","BRANCH":"\xeb\xb3\xb8\xea\xb5\x90","STATE":"\xea\xb8\xb0\xec\xa1\xb4","TYPE":"\xea\xb5\xad\xeb\xa6\xbd","POSTCODE":"","ADD_KOR":"\xec\x84\x9c\xec\x9a\xb8 \xec\xa2\x85\xeb\xa1\x9c\xea\xb5\xac \xeb\x8f\x99\xec\x88\xad\xeb\x8f\x99 \xed\x95\x9c\xea\xb5\xad\xeb\xb0\xa9\xec\x86\xa1\xed\x86\xb5\xec\x8b\xa0\xeb\x8c\x80\xed\x95\x99\xea\xb5\x90","ADD_KOR_ROAD":"","H_KOR_CITY":"\xec\x84\x9c\xec\x9a\xb8\xed\x8a\xb9\xeb\xb3\x84\xec\x8b\x9c","H_KOR_GU":"\xec\xa2\x85\xeb\xa1\x9c\xea\xb5\xac","H_KOR_DONG":"\xec\x9d\xb4\xed\x99\x94\xeb\x8f\x99","TEL":"02-3668-4114","FAX":"02-744-5882","HP":"http://www.knou.ac.kr"},{"MAIN_KEY":"BE_LiST23-0054","YEAR":"2013","CATE1_NAME":"\xec\x9d\xbc\xeb\xb0\x98\xeb\x8c\x80\xed\x95\x99","NAME_KOR":"\xed\x95\x9c\xea\xb5\xad\xec\x84\xb1\xec\x84\x9c\xeb\x8c\x80\xed\x95\x99\xea\xb5\x90","BRANCH":"\xeb\xb3\xb8\xea\xb5\x90","STATE":"\xea\xb8\xb0\xec\xa1\xb4","TYPE":"\xec\x82\xac\xeb\xa6\xbd","POSTCODE":"","ADD_KOR":"\xec\x84\x9c\xec\x9a\xb8 \xeb\x85\xb8\xec\x9b\x90\xea\xb5\xac \xec\x83\x81\xea\xb3\x847\xeb\x8f\x99 \xed\x95\x9c\xea\xb5\xad\xec\x84\xb1\xec\x84\x9c\xeb\x8c\x80\xed\x95\x99\xea\xb5\x90","ADD_KOR_ROAD":"","H_KOR_CITY":"\xec\x84\x9c\xec\x9a\xb8\xed\x8a\xb9\xeb\xb3\x84\xec\x8b\x9c","H_KOR_GU":"\xeb\x85\xb8\xec\x9b\x90\xea\xb5\xac","H_KOR_DONG":"\xec\x83\x81\xea\xb3\x846.7\xeb\x8f\x99","TEL":"02-950-5401","FAX":"02-950-5411","HP":"http://www.bible.ac.kr"},{"MAIN_KEY":"BE_LiST23-0055","YEAR":"2013","CATE1_NAME":"\xea\xb0\x81\xec\xa2\x85\xeb\x8c\x80\xed\x95\x99(\xeb\x8c\x80\xed\x95\x99)","NAME_KOR":"\xed\x95\x9c\xea\xb5\xad\xec\x98\x88\xec\x88\xa0\xec\xa2\x85\xed\x95\xa9\xed\x95\x99\xea\xb5\x90","BRANCH":"\xeb\xb3\xb8\xea\xb5\x90","STATE":"\xea\xb8\xb0\xec\xa1\xb4","TYPE":"\xed\x8a\xb9\xeb\xb3\x84\xeb\xb2\x95\xea\xb5\xad\xeb\xa6\xbd","POSTCODE":"","ADD_KOR":"\xec\x84\x9c\xec\x9a\xb8 \xec\x84\xb1\xeb\xb6\x81\xea\xb5\xac \xec\x84\x9d\xea\xb4\x80\xeb\x8f\x99 ","ADD_KOR_ROAD":"","H_KOR_CITY":"\xec\x84\x9c\xec\x9a\xb8\xed\x8a\xb9\xeb\xb3\x84\xec\x8b\x9c","H_KOR_GU":"\xec\x84\xb1\xeb\xb6\x81\xea\xb5\xac","H_KOR_DONG":"\xec\x84\x9d\xea\xb4\x80\xeb\x8f\x99","TEL":"","FAX":"","HP":""},{"MAIN_KEY":"BE_LiST23-0056","YEAR":"2013","CATE1_NAME":"\xec\x9d\xbc\xeb\xb0\x98\xeb\x8c\x80\xed\x95\x99","NAME_KOR":"\xed\x95\x9c\xea\xb5\xad\xec\x99\xb8\xea\xb5\xad\xec\x96\xb4\xeb\x8c\x80\xed\x95\x99\xea\xb5\x90","BRANCH":"\xeb\xb3\xb8\xea\xb5\x90","STATE":"\xea\xb8\xb0\xec\xa1\xb4","TYPE":"\xec\x82\xac\xeb\xa6\xbd","POSTCODE":"","ADD_KOR":"\xec\x84\x9c\xec\x9a\xb8 \xeb\x8f\x99\xeb\x8c\x80\xeb\xac\xb8\xea\xb5\xac \xec\x9d\xb4\xeb\xac\xb8\xeb\xa1\x9c 107","ADD_KOR_ROAD":"","H_KOR_CITY":"\xec\x84\x9c\xec\x9a\xb8\xed\x8a\xb9\xeb\xb3\x84\xec\x8b\x9c","H_KOR_GU":"\xeb\x8f\x99\xeb\x8c\x80\xeb\xac\xb8\xea\xb5\xac","H_KOR_DONG":"\xec\x9d\xb4\xeb\xac\xb81\xeb\x8f\x99","TEL":"02-2173-2114","FAX":"","HP":"http://www.hufs.ac.kr"},{"MAIN_KEY":"BE_LiST23-0057","YEAR":"2013","CATE1_NAME":"\xec\x9d\xbc\xeb\xb0\x98\xeb\x8c\x80\xed\x95\x99","NAME_KOR":"\xed\x95\x9c\xea\xb5\xad\xec\xb2\xb4\xec\x9c\xa1\xeb\x8c\x80\xed\x95\x99\xea\xb5\x90","BRANCH":"\xeb\xb3\xb8\xea\xb5\x90","STATE":"\xea\xb8\xb0\xec\xa1\xb4","TYPE":"\xea\xb5\xad\xeb\xa6\xbd","POSTCODE":"","ADD_KOR":"\xec\x84\x9c\xec\x9a\xb8 \xec\x86\xa1\xed\x8c\x8c\xea\xb5\xac \xec\x98\xa4\xeb\xa5\x9c\xeb\x8f\x99 \xed\x95\x9c\xea\xb5\xad\xec\xb2\xb4\xec\x9c\xa1\xeb\x8c\x80\xed\x95\x99\xea\xb5\x90","ADD_KOR_ROAD":"","H_KOR_CITY":"\xec\x84\x9c\xec\x9a\xb8\xed\x8a\xb9\xeb\xb3\x84\xec\x8b\x9c","H_KOR_GU":"\xec\x86\xa1\xed\x8c\x8c\xea\xb5\xac","H_KOR_DONG":"\xec\x98\xa4\xeb\xa5\x9c\xeb\x8f\x99","TEL":"02-410-6564","FAX":"02-410-6569","HP":"http://www.knsu.ac.kr/"},{"MAIN_KEY":"BE_LiST23-0058","YEAR":"2013","CATE1_NAME":"\xea\xb8\xb0\xeb\x8a\xa5\xeb\x8c\x80\xed\x95\x99","NAME_KOR":"\xed\x95\x9c\xea\xb5\xad\xed\x8f\xb4\xeb\xa6\xac\xed\x85\x8d I \xeb\x8c\x80\xed\x95\x99 \xec\x84\x9c\xec\x9a\xb8\xea\xb0\x95\xec\x84\x9c\xec\xba\xa0\xed\x8d\xbc\xec\x8a\xa4","BRANCH":"\xeb\xb3\xb8\xea\xb5\x90","STATE":"\xea\xb8\xb0\xec\xa1\xb4","TYPE":"\xec\x82\xac\xeb\xa6\xbd","POSTCODE":"","ADD_KOR":"\xec\x84\x9c\xec\x9a\xb8 \xea\xb0\x95\xec\x84\x9c\xea\xb5\xac \xed\x99\x94\xea\xb3\xa1\xeb\x8f\x99 \xec\x82\xb060-1","ADD_KOR_ROAD":"","H_KOR_CITY":"\xec\x84\x9c\xec\x9a\xb8\xed\x8a\xb9\xeb\xb3\x84\xec\x8b\x9c","H_KOR_GU":"\xea\xb0\x95\xec\x84\x9c\xea\xb5\xac","H_KOR_DONG":"\xec\x9a\xb0\xec\x9e\xa5\xec\x82\xb0\xeb\x8f\x99","TEL":"02-2186-5800","FAX":"02-2186-5819","HP":"http://kangseo.kopo.ac.kr"},{"MAIN_KEY":"BE_LiST23-0059","YEAR":"2013","CATE1_NAME":"\xea\xb8\xb0\xeb\x8a\xa5\xeb\x8c\x80\xed\x

In [7]:
data = r.json()
data

{'SebcCollegeInfoKor': {'list_total_count': 64,
  'RESULT': {'CODE': 'INFO-000', 'MESSAGE': '정상 처리되었습니다'},
  'row': [{'MAIN_KEY': 'BE_LiST23-0034',
    'YEAR': '2013',
    'CATE1_NAME': '일반대학',
    'NAME_KOR': '서울시립대학교',
    'BRANCH': '본교',
    'STATE': '기존',
    'TYPE': '공립',
    'POSTCODE': '',
    'ADD_KOR': '서울 동대문구 서울시립대로 163 (전농동 90번지) ',
    'ADD_KOR_ROAD': '',
    'H_KOR_CITY': '서울특별시',
    'H_KOR_GU': '동대문구',
    'H_KOR_DONG': '휘경2동',
    'TEL': '02-6490-6114',
    'FAX': '02-2210-5576',
    'HP': 'http://www.uos.ac.kr'},
   {'MAIN_KEY': 'BE_LiST23-0035',
    'YEAR': '2013',
    'CATE1_NAME': '전문대학(3년제)',
    'NAME_KOR': '서울여자간호대학교',
    'BRANCH': '본교',
    'STATE': '기존',
    'TYPE': '사립',
    'POSTCODE': '',
    'ADD_KOR': '서울 서대문구 홍제3동 서울여자간호대학',
    'ADD_KOR_ROAD': '',
    'H_KOR_CITY': '서울특별시',
    'H_KOR_GU': '서대문구',
    'H_KOR_DONG': '홍제2동',
    'TEL': '02-2287-1700',
    'FAX': '02-395-8018',
    'HP': 'http://www.snjc.ac.kr'},
   {'MAIN_KEY': 'BE_LiST23-0036',
    'YEAR': '2013',
    'CATE1_NAME': '일반대학',
    'NAME_KOR': '서울여자대학교',
    'BRANCH': '본교',
    'STATE': '기존',
    'TYPE': '사립',
    'POSTCODE': '',
    'ADD_KOR': '서울특별시 노원구 화랑로 621 서울여자대학교',
    'ADD_KOR_ROAD': '',
    'H_KOR_CITY': '서울특별시',
    'H_KOR_GU': '노원구',
    'H_KOR_DONG': '공릉2동',
    'TEL': '02-970-5114',
    'FAX': '02-978-7931',
    'HP': 'http://www.swu.ac.kr'},
   {'MAIN_KEY': 'BE_LiST23-0037',
    'YEAR': '2013',
    'CATE1_NAME': '전문대학(2년제)',
    'NAME_KOR': '서일대학교',
    'BRANCH': '본교',
    'STATE': '학교명 변경',
    'TYPE': '사립',
    'POSTCODE': '',
    'ADD_KOR': '서울 중랑구 서일대학길 22(면목동 49-3) 서일대학교',
    'ADD_KOR_ROAD': '',
    'H_KOR_CITY': '서울특별시',
    'H_KOR_GU': '중랑구',
    'H_KOR_DONG': '면목제3.8동',
    'TEL': '02-490-7300',
    'FAX': '02-493-2576',
    'HP': 'http://www.seoil.ac.kr'},
   {'MAIN_KEY': 'BE_LiST23-0038',
    'YEAR': '2013',
    'CATE1_NAME': '일반대학',
    'NAME_KOR': '성공회대학교',
    'BRANCH': '본교',
    'STATE': '기존',
    'TYPE': '사립',
    'POSTCODE': '',
    'ADD_KOR': '서울 구로구 항동 성공회대학교',
    'ADD_KOR_ROAD': '',
    'H_KOR_CITY': '서울특별시',
    'H_KOR_GU': '구로구',
    'H_KOR_DONG': '오류2동',
    'TEL': '02-2610-4142',
    'FAX': '02-2610-4248',
    'HP': 'http://www.skhu.ac.kr'},
   {'MAIN_KEY': 'BE_LiST23-0039',
    'YEAR': '2013',
    'CATE1_NAME': '일반대학',
    'NAME_KOR': '성균관대학교',
    'BRANCH': '본교',
    'STATE': '기존',
    'TYPE': '사립',
    'POSTCODE': '',
    'ADD_KOR': '서울 종로구 명륜동3가 성균관대학교',
    'ADD_KOR_ROAD': '',
    'H_KOR_CITY': '서울특별시',
    'H_KOR_GU': '종로구',
    'H_KOR_DONG': '종로1.2.3.4가동',
    'TEL': '02-760-0114',
    'FAX': '',
    'HP': 'http://www.skku.edu'},
   {'MAIN_KEY': 'BE_LiST23-0040',
    'YEAR': '2013',
    'CATE1_NAME': '일반대학',
    'NAME_KOR': '성신여자대학교',
    'BRANCH': '본교',
    'STATE': '기존',
    'TYPE': '사립',
    'POSTCODE': '',
    'ADD_KOR': '서울 성북구 동선동3가 성신여자대학교',
    'ADD_KOR_ROAD': '',
    'H_KOR_CITY': '서울특별시',
    'H_KOR_GU': '성북구',
    'H_KOR_DONG': '동선동',
    'TEL': '02-920-7114',
    'FAX': '02-920-2018',
    'HP': 'http://www.sungshin.ac.kr'},
   {'MAIN_KEY': 'BE_LiST23-0041',
    'YEAR': '2013',
    'CATE1_NAME': '일반대학',
    'NAME_KOR': '세종대학교',
    'BRANCH': '본교',
    'STATE': '기존',
    'TYPE': '사립',
    'POSTCODE': '',
    'ADD_KOR': '서울 광진구 군자동 세종대학교',
    'ADD_KOR_ROAD': '',
    'H_KOR_CITY': '서울특별시',
    'H_KOR_GU': '광진구',
    'H_KOR_DONG': '군자동',
    'TEL': '02-3408-3114',
    'FAX': '02-3408-3906',
    'HP': 'http://www.sejong.ac.kr'},
   {'MAIN_KEY': 'BE_LiST23-0042',
    'YEAR': '2013',
    'CATE1_NAME': '일반대학',
    'NAME_KOR': '숙명여자대학교',
    'BRANCH': '본교',
    'STATE': '기존',
    'TYPE': '사립',
    'POSTCODE': '',
    'ADD_KOR': '서울 용산구 청파로47길 100 숙명여자대학교',
    'ADD_KOR_ROAD': '',
    'H_KOR_CITY': '서울특별시',
    'H_KOR_GU': '용산구',
    'H_KOR_DONG': '청파동',
    'TEL': '',
    'FAX': '',
    'HP': 'http://www.sookmyung.ac.kr/'},
   {'MAIN_KEY': 'BE_LiST23-0043',
    'YEAR': '2013',
    'CATE1_NAME': '일반대학',
    'NAME_KOR': '숭실대학교',
    'BRANCH': '본교',
    'STATE': '기존',
    'TYPE': '사립',
    'POSTCODE': '',
    'ADD_KOR': '서울 동작구 상도동 511 숭실대학교',
    'ADD_KOR_ROAD': '',
    'H_KOR_CITY': '서울특별시',
    'H_KOR_GU': '동작구',
    'H_KOR_DONG': '상도1동',
    'TEL': '02-820-0114',
    'FAX': '',
    'HP': 'http://www.ssu.ac.kr'},
   {'MAIN_KEY': 'BE_LiST23-0044',
    'YEAR': '2013',
    'CATE1_NAME': '전문대학(2년제)',
    'NAME_KOR': '숭의여자대학교',
    'BRANCH': '본교',
    'STATE': '기존',
    'TYPE': '사립',
    'POSTCODE': '',
    'ADD_KOR': '서울특별시 중구 소파로2길 10(예장동)',
    'ADD_KOR_ROAD': '',
    'H_KOR_CITY': '서울특별시',
    'H_KOR_GU': '중구',
    'H_KOR_DONG': '필동',
    'TEL': '02-3708-9000',
    'FAX': '02-773-2625',
    'HP': 'http://www.sewc.ac.kr'},
   {'MAIN_KEY': 'BE_LiST23-0045',
    'YEAR': '2013',
    'CATE1_NAME': '일반대학',
    'NAME_KOR': '연세대학교',
    'BRANCH': '본교',
    'STATE': '기존',
    'TYPE': '사립',
    'POSTCODE': '',
    'ADD_KOR': '서울 서대문구 신촌동 연세대학교',
    'ADD_KOR_ROAD': '',
    'H_KOR_CITY': '서울특별시',
    'H_KOR_GU': '서대문구',
    'H_KOR_DONG': '신촌동',
    'TEL': '02-2123-2114',
    'FAX': '02-392-0618',
    'HP': 'http://www.yonsei.ac.kr'},
   {'MAIN_KEY': 'BE_LiST23-0046',
    'YEAR': '2013',
    'CATE1_NAME': '일반대학',
    'NAME_KOR': '이화여자대학교',
    'BRANCH': '본교',
    'STATE': '기존',
    'TYPE': '사립',
    'POSTCODE': '',
    'ADD_KOR': '서울 서대문구 대현동 11-1 이화여자대학교',
    'ADD_KOR_ROAD': '',
    'H_KOR_CITY': '서울특별시',
    'H_KOR_GU': '서대문구',
    'H_KOR_DONG': '신촌동',
    'TEL': '02-3277-2114',
    'FAX': '02-393-5903',
    'HP': 'http://www.ewha.ac.kr'},
   {'MAIN_KEY': 'BE_LiST23-0047',
    'YEAR': '2013',
    'CATE1_NAME': '전문대학(2년제)',
    'NAME_KOR': '인덕대학교',
    'BRANCH': '본교',
    'STATE': '기존',
    'TYPE': '사립',
    'POSTCODE': '',
    'ADD_KOR': '서울 노원구 초안산로 12',
    'ADD_KOR_ROAD': '',
    'H_KOR_CITY': '서울특별시',
    'H_KOR_GU': '노원구',
    'H_KOR_DONG': '월계2동',
    'TEL': '02-950-7000',
    'FAX': '02-906-5340',
    'HP': 'http://www.induk.ac.kr'},
   {'MAIN_KEY': 'BE_LiST23-0048',
    'YEAR': '2013',
    'CATE1_NAME': '일반대학',
    'NAME_KOR': '장로회신학대학교',
    'BRANCH': '본교',
    'STATE': '기존',
    'TYPE': '사립',
    'POSTCODE': '',
    'ADD_KOR': '서울 광진구 광장로 5길 25-1(광장동) 장로회신학대학교',
    'ADD_KOR_ROAD': '',
    'H_KOR_CITY': '서울특별시',
    'H_KOR_GU': '광진구',
    'H_KOR_DONG': '광장동',
    'TEL': '02-450-0700',
    'FAX': '',
    'HP': 'http://www.pcts.ac.kr'},
   {'MAIN_KEY': 'BE_LiST23-0049',
    'YEAR': '2013',
    'CATE1_NAME': '전문대학(3년제)',
    'NAME_KOR': '적십자간호대학',
    'BRANCH': '본교',
    'STATE': '폐교',
    'TYPE': '사립',
    'POSTCODE': '',
    'ADD_KOR': '서울 종로구 경교장길8',
    'ADD_KOR_ROAD': '',
    'H_KOR_CITY': '서울특별시',
    'H_KOR_GU': '종로구',
    'H_KOR_DONG': '교남동',
    'TEL': '02-3700-3600',
    'FAX': '02-3700-3400',
    'HP': 'http://redcross.cau.ac.kr'},
   {'MAIN_KEY': 'BE_LiST23-0050',
    'YEAR': '2013',
    'CATE1_NAME': '일반대학',
    'NAME_KOR': '중앙대학교 서울캠퍼스',
    'BRANCH': '본교',
    'STATE': '기존',
    'TYPE': '사립',
    'POSTCODE': '',
    'ADD_KOR': '서울 동작구 흑석로 84',
    'ADD_KOR_ROAD': '',
    'H_KOR_CITY': '서울특별시',
    'H_KOR_GU': '동작구',
    'H_KOR_DONG': '흑석동',
    'TEL': '02-820-5114',
    'FAX': '',
    'HP': 'http://www.cau.ac.kr'},
   {'MAIN_KEY': 'BE_LiST23-0051',
    'YEAR': '2013',
    'CATE1_NAME': '일반대학',
    'NAME_KOR': '총신대학교',
    'BRANCH': '본교',
    'STATE': '기존',
    'TYPE': '사립',
    'POSTCODE': '',
    'ADD_KOR': '서울 동작구 사당동 산31-3',
    'ADD_KOR_ROAD': '',
    'H_KOR_CITY': '서울특별시',
    'H_KOR_GU': '동작구',
    'H_KOR_DONG': '사당3동',
    'TEL': '02-3479-0200',
    'FAX': '02-536-2602',
    'HP': 'http://www.chongshin.ac.kr'},
   {'MAIN_KEY': 'BE_LiST23-0052',
    'YEAR': '2013',
    'CATE1_NAME': '일반대학',
    'NAME_KOR': '추계예술대학교',
    'BRANCH': '본교',
    'STATE': '기존',
    'TYPE': '사립',
    'POSTCODE': '',
    'ADD_KOR': '서울 서대문구 북아현동 190-1 추계예술대학교',
    'ADD_KOR_ROAD': '',
    'H_KOR_CITY': '서울특별시',
    'H_KOR_GU': '서대문구',
    'H_KOR_DONG': '충현동',
    'TEL': '02-362-5700',
    'FAX': '02-392-1777',
    'HP': 'http://www.chugye.ac.kr'},
   {'MAIN_KEY': 'BE_LiST23-0053',
    'YEAR': '2013',
    'CATE1_NAME': '방송통신대학',
    'NAME_KOR': '한국방송통신대학교',
    'BRANCH': '본교',
    'STATE': '기존',
    'TYPE': '국립',
    'POSTCODE': '',
    'ADD_KOR': '서울 종로구 동숭동 한국방송통신대학교',
    'ADD_KOR_ROAD': '',
    'H_KOR_CITY': '서울특별시',
    'H_KOR_GU': '종로구',
    'H_KOR_DONG': '이화동',
    'TEL': '02-3668-4114',
    'FAX': '02-744-5882',
    'HP': 'http://www.knou.ac.kr'},
   {'MAIN_KEY': 'BE_LiST23-0054',
    'YEAR': '2013',
    'CATE1_NAME': '일반대학',
    'NAME_KOR': '한국성서대학교',
    'BRANCH': '본교',
    'STATE': '기존',
    'TYPE': '사립',
    'POSTCODE': '',
    'ADD_KOR': '서울 노원구 상계7동 한국성서대학교',
    'ADD_KOR_ROAD': '',
    'H_KOR_CITY': '서울특별시',
    'H_KOR_GU': '노원구',
    'H_KOR_DONG': '상계6.7동',
    'TEL': '02-950-5401',
    'FAX': '02-950-5411',
    'HP': 'http://www.bible.ac.kr'},
   {'MAIN_KEY': 'BE_LiST23-0055',
    'YEAR': '2013',
    'CATE1_NAME': '각종대학(대학)',
    'NAME_KOR': '한국예술종합학교',
    'BRANCH': '본교',
    'STATE': '기존',
    'TYPE': '특별법국립',
    'POSTCODE': '',
    'ADD_KOR': '서울 성북구 석관동 ',
    'ADD_KOR_ROAD': '',
    'H_KOR_CITY': '서울특별시',
    'H_KOR_GU': '성북구',
    'H_KOR_DONG': '석관동',
    'TEL': '',
    'FAX': '',
    'HP': ''},
   {'MAIN_KEY': 'BE_LiST23-0056',
    'YEAR': '2013',
    'CATE1_NAME': '일반대학',
    'NAME_KOR': '한국외국어대학교',
    'BRANCH': '본교',
    'STATE': '기존',
    'TYPE': '사립',
    'POSTCODE': '',
    'ADD_KOR': '서울 동대문구 이문로 107',
    'ADD_KOR_ROAD': '',
    'H_KOR_CITY': '서울특별시',
    'H_KOR_GU': '동대문구',
    'H_KOR_DONG': '이문1동',
    'TEL': '02-2173-2114',
    'FAX': '',
    'HP': 'http://www.hufs.ac.kr'},
   {'MAIN_KEY': 'BE_LiST23-0057',
    'YEAR': '2013',
    'CATE1_NAME': '일반대학',
    'NAME_KOR': '한국체육대학교',
    'BRANCH': '본교',
    'STATE': '기존',
    'TYPE': '국립',
    'POSTCODE': '',
    'ADD_KOR': '서울 송파구 오륜동 한국체육대학교',
    'ADD_KOR_ROAD': '',
    'H_KOR_CITY': '서울특별시',
    'H_KOR_GU': '송파구',
    'H_KOR_DONG': '오륜동',
    'TEL': '02-410-6564',
    'FAX': '02-410-6569',
    'HP': 'http://www.knsu.ac.kr/'},
   {'MAIN_KEY': 'BE_LiST23-0058',
    'YEAR': '2013',
    'CATE1_NAME': '기능대학',
    'NAME_KOR': '한국폴리텍 I 대학 서울강서캠퍼스',
    'BRANCH': '본교',
    'STATE': '기존',
    'TYPE': '사립',
    'POSTCODE': '',
    'ADD_KOR': '서울 강서구 화곡동 산60-1',
    'ADD_KOR_ROAD': '',
    'H_KOR_CITY': '서울특별시',
    'H_KOR_GU': '강서구',
    'H_KOR_DONG': '우장산동',
    'TEL': '02-2186-5800',
    'FAX': '02-2186-5819',
    'HP': 'http://kangseo.kopo.ac.kr'},
   {'MAIN_KEY': 'BE_LiST23-0059',
    'YEAR': '2013',
    'CATE1_NAME': '기능대학',
    'NAME_KOR': '한국폴리텍Ⅰ대학 서울정수캠퍼스',
    'BRANCH': '본교',
    'STATE': '기존',
    'TYPE': '사립',
    'POSTCODE': '',
    'ADD_KOR': '서울 용산구 보광로 73(보광동 238)',
    'ADD_KOR_ROAD': '',
    'H_KOR_CITY': '서울특별시',
    'H_KOR_GU': '용산구',
    'H_KOR_DONG': '보광동',
    'TEL': '02-2001-4000',
    'FAX': '02-2001-4119',
    'HP': 'http://jungsu.kopo.ac.kr'},
   {'MAIN_KEY': 'BE_LiST23-0060',
    'YEAR': '2013',
    'CATE1_NAME': '일반대학',
    'NAME_KOR': '한성대학교',
    'BRANCH': '본교',
    'STATE': '기존',
    'TYPE': '사립',
    'POSTCODE': '',
    'ADD_KOR': '서울 성북구 삼선동3가 389 한성대학교',
    'ADD_KOR_ROAD': '',
    'H_KOR_CITY': '서울특별시',
    'H_KOR_GU': '성북구',
    'H_KOR_DONG': '삼선동',
    'TEL': '02-760-4231',
    'FAX': '02-745-8943',
    'HP': 'http://www.hansung.ac.kr'},
   {'MAIN_KEY': 'BE_LiST23-0061',
    'YEAR': '2013',
    'CATE1_NAME': '일반대학',
    'NAME_KOR': '한양대학교',
    'BRANCH': '본교',
    'STATE': '기존',
    'TYPE': '사립',
    'POSTCODE': '',
    'ADD_KOR': '서울특별시 성동구 왕십리로 222 ',
    'ADD_KOR_ROAD': '',
    'H_KOR_CITY': '서울특별시',
    'H_KOR_GU': '성동구',
    'H_KOR_DONG': '사근동',
    'TEL': '02-2220-0114',
    'FAX': '',
    'HP': 'http://www.hanyang.ac.kr'},
   {'MAIN_KEY': 'BE_LiST23-0062',
    'YEAR': '2013',
    'CATE1_NAME': '전문대학(2년제)',
    'NAME_KOR': '한양여자대학교',
    'BRANCH': '본교',
    'STATE': '기존',
    'TYPE': '사립',
    'POSTCODE': '',
    'ADD_KOR': '서울 성동구 행당동 살곶이길 200',
    'ADD_KOR_ROAD': '',
    'H_KOR_CITY': '서울특별시',
    'H_KOR_GU': '성동구',
    'H_KOR_DONG': '사근동',
    'TEL': '02-2290-2114',
    'FAX': '02-2291-6111',
    'HP': 'http://www.hywoman.ac.kr'},
   {'MAIN_KEY': 'BE_LiST23-0063',
    'YEAR': '2013',
    'CATE1_NAME': '일반대학',
    'NAME_KOR': '한영신학대학교',
    'BRANCH': '본교',
    'STATE': '기존',
    'TYPE': '사립',
    'POSTCODE': '',
    'ADD_KOR': '서울 구로구 경인로 290-42  한영신학대학교',
    'ADD_KOR_ROAD': '',
    'H_KOR_CITY': '서울특별시',
    'H_KOR_GU': '구로구',
    'H_KOR_DONG': '개봉1동',
    'TEL': '02-2067-4500',
    'FAX': '02-2616-4102',
    'HP': 'http://www.hytu.ac.kr'},
   {'MAIN_KEY': 'BE_LiST23-0064',
    'YEAR': '2013',
    'CATE1_NAME': '일반대학',
    'NAME_KOR': '홍익대학교',
    'BRANCH': '본교',
    'STATE': '기존',
    'TYPE': '사립',
    'POSTCODE': '',
    'ADD_KOR': '서울특별시 마포구 와우산로 94(상수동)',
    'ADD_KOR_ROAD': '',
    'H_KOR_CITY': '서울특별시',
    'H_KOR_GU': '마포구',
    'H_KOR_DONG': '서강동',
    'TEL': '02-320-1114',
    'FAX': '02-320-1122',
    'HP': 'http://www.hongik.ac.kr/'},
   {'MAIN_KEY': 'BE_LiST23-0001',
    'YEAR': '2013',
    'CATE1_NAME': '일반대학',
    'NAME_KOR': '가톨릭대학교',
    'BRANCH': '제2캠퍼스',
    'STATE': '기존',
    'TYPE': '사립',
    'POSTCODE': '',
    'ADD_KOR': '서울 서초구 반포동 505',
    'ADD_KOR_ROAD': '',
    'H_KOR_CITY': '서울특별시',
    'H_KOR_GU': '서초구',
    'H_KOR_DONG': '반포4동',
    'TEL': '',
    'FAX': '',
    'HP': 'http://songeui.catholic.ac.kr'},
   {'MAIN_KEY': 'BE_LiST23-0002',
    'YEAR': '2013',
    'CATE1_NAME': '일반대학',
    'NAME_KOR': '가톨릭대학교',
    'BRANCH': '제3캠퍼스',
    'STATE': '기존',
    'TYPE': '사립',
    'POSTCODE': '',
    'ADD_KOR': '서울 종로구 창경궁로 296-12(혜화동) ',
    'ADD_KOR_ROAD': '',
    'H_KOR_CITY': '서울특별시',
    'H_KOR_GU': '종로구',
    'H_KOR_DONG': '이화동',
    'TEL': '02-740-9714',
    'FAX': '02-741-2801',
    'HP': 'http://catholic.ac.kr'},
   {'MAIN_KEY': 'BE_LiST23-0003',
    'YEAR': '2013',
    'CATE1_NAME': '일반대학',
    'NAME_KOR': '감리교신학대학교',
    'BRANCH': '본교',
    'STATE': '기존',
    'TYPE': '사립',
    'POSTCODE': '',
    'ADD_KOR': '서울 서대문구 냉천동 감리교신학대학',
    'ADD_KOR_ROAD': '',
    'H_KOR_CITY': '서울특별시',
    'H_KOR_GU': '서대문구',
    'H_KOR_DONG': '천연동',
    'TEL': '02-361-9114',
    'FAX': '02-361-9299',
    'HP': 'http://www.mtu.ac.kr'},
   {'MAIN_KEY': 'BE_LiST23-0004',
    'YEAR': '2013',
    'CATE1_NAME': '일반대학',
    'NAME_KOR': '건국대학교',
    'BRANCH': '본교',
    'STATE': '기존',
    'TYPE': '사립',
    'POSTCODE': '',
    'ADD_KOR': '서울 광진구 화양동',
    'ADD_KOR_ROAD': '',
    'H_KOR_CITY': '서울특별시',
    'H_KOR_GU': '광진구',
    'H_KOR_DONG': '화양동',
    'TEL': '02-450-3114',
    'FAX': '02-450-4126',
    'HP': 'http://www.konkuk.ac.kr'},
   {'MAIN_KEY': 'BE_LiST23-0005',
    'YEAR': '2013',
    'CATE1_NAME': '일반대학',
    'NAME_KOR': '경기대학교',
    'BRANCH': '제2캠퍼스',
    'STATE': '기존',
    'TYPE': '사립',
    'POSTCODE': '',
    'ADD_KOR': '서울 서대문구 경기대로9길 24 경기대학교',
    'ADD_KOR_ROAD': '',
    'H_KOR_CITY': '서울특별시',
    'H_KOR_GU': '서대문구',
    'H_KOR_DONG': '충현동',
    'TEL': '02-390-5114',
    'FAX': '031-249-8718',
    'HP': 'http://www.kyonggi.ac.kr'},
   {'MAIN_KEY': 'BE_LiST23-0006',
    'YEAR': '2013',
    'CATE1_NAME': '일반대학',
    'NAME_KOR': '경희대학교',
    'BRANCH': '본교',
    'STATE': '기존',
    'TYPE': '사립',
    'POSTCODE': '',
    'ADD_KOR': '서울 동대문구 회기동 경희대학교',
    'ADD_KOR_ROAD': '',
    'H_KOR_CITY': '서울특별시',
    'H_KOR_GU': '동대문구',
    'H_KOR_DONG': '회기동',
    'TEL': '02-961-0114',
    'FAX': '02-961-0930',
    'HP': 'http://www.khu.ac.kr'},
   {'MAIN_KEY': 'BE_LiST23-0007',
    'YEAR': '2013',
    'CATE1_NAME': '일반대학',
    'NAME_KOR': '고려대학교',
    'BRANCH': '본교',
    'STATE': '기존',
    'TYPE': '사립',
    'POSTCODE': '',
    'ADD_KOR': '서울 성북구 안암동 고려대학교',
    'ADD_KOR_ROAD': '',
    'H_KOR_CITY': '서울특별시',
    'H_KOR_GU': '성북구',
    'H_KOR_DONG': '안암동',
    'TEL': '02-3290-1114',
    'FAX': '',
    'HP': 'http://www.korea.ac.kr'},
   {'MAIN_KEY': 'BE_LiST23-0008',
    'YEAR': '2013',
    'CATE1_NAME': '일반대학',
    'NAME_KOR': '광운대학교',
    'BRANCH': '본교',
    'STATE': '기존',
    'TYPE': '사립',
    'POSTCODE': '',
    'ADD_KOR': '서울특별시 노원구 월계동 447-1',
    'ADD_KOR_ROAD': '',
    'H_KOR_CITY': '서울특별시',
    'H_KOR_GU': '노원구',
    'H_KOR_DONG': '월계1동',
    'TEL': '',
    'FAX': '',
    'HP': 'http://www.kw.ac.kr'},
   {'MAIN_KEY': 'BE_LiST23-0009',
    'YEAR': '2013',
    'CATE1_NAME': '일반대학',
    'NAME_KOR': '국민대학교',
    'BRANCH': '본교',
    'STATE': '기존',
    'TYPE': '사립',
    'POSTCODE': '',
    'ADD_KOR': '서울 성북구 정릉3동 국민대학교',
    'ADD_KOR_ROAD': '',
    'H_KOR_CITY': '서울특별시',
    'H_KOR_GU': '성북구',
    'H_KOR_DONG': '정릉3동',
    'TEL': '02-910-4114',
    'FAX': '',
    'HP': 'http://www.kookmin.ac.kr'},
   {'MAIN_KEY': 'BE_LiST23-0010',
    'YEAR': '2013',
    'CATE1_NAME': '전공대학',
    'NAME_KOR': '국제예술대학',
    'BRANCH': '본교',
    'STATE': '기존',
    'TYPE': '사립',
    'POSTCODE': '',
    'ADD_KOR': '서울 강남구 논현동 79',
    'ADD_KOR_ROAD': '',
    'H_KOR_CITY': '서울특별시',
    'H_KOR_GU': '강남구',
    'H_KOR_DONG': '논현2동',
    'TEL': '02-542-8197',
    'FAX': '02-517-1392',
    'HP': 'http://www.kica.ac.kr'},
   {'MAIN_KEY': 'BE_LiST23-0011',
    'YEAR': '2013',
    'CATE1_NAME': '일반대학',
    'NAME_KOR': '그리스도대학교',
    'BRANCH': '본교',
    'STATE': '기존',
    'TYPE': '사립',
    'POSTCODE': '',
    'ADD_KOR': '서울 강서구 화곡6동 그리스도대학교',
    'ADD_KOR_ROAD': '',
    'H_KOR_CITY': '서울특별시',
    'H_KOR_GU': '강서구',
    'H_KOR_DONG': '화곡본동',
    'TEL': '02-2600-2400',
    'FAX': '02-2698-8876',
    'HP': 'http://kcu.ac.kr'},
   {'MAIN_KEY': 'BE_LiST23-0012',
    'YEAR': '2013',
    'CATE1_NAME': '일반대학',
    'NAME_KOR': '덕성여자대학교',
    'BRANCH': '본교',
    'STATE': '기존',
    'TYPE': '사립',
    'POSTCODE': '',
    'ADD_KOR': '서울특별시 도봉구 삼양로 144길 33',
    'ADD_KOR_ROAD': '',
    'H_KOR_CITY': '서울특별시',
    'H_KOR_GU': '도봉구',
    'H_KOR_DONG': '쌍문1동',
    'TEL': '02-901-8000',
    'FAX': '',
    'HP': 'http://www.duksung.ac.kr'},
   {'MAIN_KEY': 'BE_LiST23-0013',
    'YEAR': '2013',
    'CATE1_NAME': '일반대학',
    'NAME_KOR': '동국대학교',
    'BRANCH': '본교',
    'STATE': '기존',
    'TYPE': '사립',
    'POSTCODE': '',
    'ADD_KOR': '서울 중구 필동3가 동국대학교',
    'ADD_KOR_ROAD': '',
    'H_KOR_CITY': '서울특별시',
    'H_KOR_GU': '중구',
    'H_KOR_DONG': '필동',
    'TEL': '02-2260-3114',
    'FAX': '02-2277-1274',
    'HP': 'http://www.dongguk.edu'},
   {'MAIN_KEY': 'BE_LiST23-0014',
    'YEAR': '2013',
    'CATE1_NAME': '일반대학',
    'NAME_KOR': '동덕여자대학교',
    'BRANCH': '본교',
    'STATE': '기존',
    'TYPE': '사립',
    'POSTCODE': '',
    'ADD_KOR': '서울 성북구 하월곡2동 동덕여자대학교',
    'ADD_KOR_ROAD': '',
    'H_KOR_CITY': '서울특별시',
    'H_KOR_GU': '성북구',
    'H_KOR_DONG': '삼선동',
    'TEL': '02-940-4000',
    'FAX': '02-940-4182',
    'HP': 'http://www.dongduk.ac.kr'},
   {'MAIN_KEY': 'BE_LiST23-0015',
    'YEAR': '2013',
    'CATE1_NAME': '전문대학(3년제)',
    'NAME_KOR': '동양미래대학교',
    'BRANCH': '본교',
    'STATE': '기존',
    'TYPE': '사립',
    'POSTCODE': '',
    'ADD_KOR': '서울시 구로구 경인로 445 동양미래대학교 (고척동 62-160)',
    'ADD_KOR_ROAD': '',
    'H_KOR_CITY': '서울특별시',
    'H_KOR_GU': '구로구',
    'H_KOR_DONG': '고척1동',
    'TEL': '02-2610-1700',
    'FAX': '02-2688-5494',
    'HP': 'http://www.dongyang.ac.kr/'},
   {'MAIN_KEY': 'BE_LiST23-0016',
    'YEAR': '2013',
    'CATE1_NAME': '사이버대학(대학)',
    'NAME_KOR': '디지털서울문화예술대학교',
    'BRANCH': '본교',
    'STATE': '기존',
    'TYPE': '사립',
    'POSTCODE': '',
    'ADD_KOR': '서울시 서대문구 통일로 37길 60 (홍제동 318-18)',
    'ADD_KOR_ROAD': '',
    'H_KOR_CITY': '서울특별시',
    'H_KOR_GU': '서대문구',
    'H_KOR_DONG': '홍제1동',
    'TEL': '02-2287-0222',
    'FAX': '02-379-8828',
    'HP': 'http://www.scau.ac.kr'},
   {'MAIN_KEY': 'BE_LiST23-0017',
    'YEAR': '2013',
    'CATE1_NAME': '일반대학',
    'NAME_KOR': '명지대학교 인문캠퍼스',
    'BRANCH': '제2캠퍼스',
    'STATE': '기존',
    'TYPE': '사립',
    'POSTCODE': '',
    'ADD_KOR': '서울 서대문구 남가좌동 50-3',
    'ADD_KOR_ROAD': '',
    'H_KOR_CITY': '서울특별시',
    'H_KOR_GU': '서대문구',
    'H_KOR_DONG': '남가좌2동',
    'TEL': '02-300-1556',
    'FAX': '02-300-1556',
    'HP': 'http://www.mju.ac.kr'},
   {'MAIN_KEY': 'BE_LiST23-0018',
    'YEAR': '2013',
    'CATE1_NAME': '전문대학(3년제)',
    'NAME_KOR': '명지전문대학',
    'BRANCH': '본교',
    'STATE': '기존',
    'TYPE': '사립',
    'POSTCODE': '',

In [9]:
import pandas as pd
temp = []
for d in data['SebcCollegeInfoKor']['row']:
  temp.append(d)
uni = pd.DataFrame(temp)
uni.head()

,MAIN_KEY,YEAR,CATE1_NAME,NAME_KOR,BRANCH,STATE,TYPE,POSTCODE,ADD_KOR,ADD_KOR_ROAD,H_KOR_CITY,H_KOR_GU,H_KOR_DONG,TEL,FAX,HP
0,BE_LiST23-0034,2013,일반대학,서울시립대학교,본교,기존,공립,,서울 동대문구 서울시립대로 163 (전농동 90번지),,서울특별시,동대문구,휘경2동,02-6490-6114,02-2210-5576,http://www.uos.ac.kr
1,BE_LiST23-0035,2013,전문대학(3년제),서울여자간호대학교,본교,기존,사립,,서울 서대문구 홍제3동 서울여자간호대학,,서울특별시,서대문구,홍제2동,02-2287-1700,02-395-8018,http://www.snjc.ac.kr
2,BE_LiST23-0036,2013,일반대학,서울여자대학교,본교,기존,사립,,서울특별시 노원구 화랑로 621 서울여자대학교,,서울특별시,노원구,공릉2동,02-970-5114,02-978-7931,http://www.swu.ac.kr
3,BE_LiST23-0037,2013,전문대학(2년제),서일대학교,본교,학교명 변경,사립,,서울 중랑구 서일대학길 22(면목동 49-3) 서일대학교,,서울특별시,중랑구,면목제3.8동,02-490-7300,02-493-2576,http://www.seoil.ac.kr
4,BE_LiST23-0038,2013,일반대학,성공회대학교,본교,기존,사립,,서울 구로구 항동 성공회대학교,,서울특별시,구로구,오류2동,02-2610-4142,02-2610-4248,http://www.skhu.ac.kr

In [16]:
import requests

url = 'http://openapi.seoul.go.kr:8088/4768796e76646f6738376c4d4a6153/json/subwayStationMaster/1/1000/'
m = requests.get(url)

In [17]:
print(m.content)

b'{"subwayStationMaster":{"list_total_count":909,"RESULT":{"CODE":"INFO-000","MESSAGE":"\xec\xa0\x95\xec\x83\x81 \xec\xb2\x98\xeb\xa6\xac\xeb\x90\x98\xec\x97\x88\xec\x8a\xb5\xeb\x8b\x88\xeb\x8b\xa4"},"row":[{"BLDN_ID":"0150","BLDN_NM":"\xec\x84\x9c\xec\x9a\xb8\xec\x97\xad","ROUTE":"1\xed\x98\xb8\xec\x84\xa0","LAT":"37.556228","LOT":"126.972135"},{"BLDN_ID":"0151","BLDN_NM":"\xec\x8b\x9c\xec\xb2\xad","ROUTE":"1\xed\x98\xb8\xec\x84\xa0","LAT":"37.565715","LOT":"126.977088"},{"BLDN_ID":"0152","BLDN_NM":"\xec\xa2\x85\xea\xb0\x81","ROUTE":"1\xed\x98\xb8\xec\x84\xa0","LAT":"37.570161","LOT":"126.982923"},{"BLDN_ID":"0153","BLDN_NM":"\xec\xa2\x85\xeb\xa1\x9c3\xea\xb0\x80","ROUTE":"1\xed\x98\xb8\xec\x84\xa0","LAT":"37.570406","LOT":"126.991847"},{"BLDN_ID":"0154","BLDN_NM":"\xec\xa2\x85\xeb\xa1\x9c5\xea\xb0\x80","ROUTE":"1\xed\x98\xb8\xec\x84\xa0","LAT":"37.570926","LOT":"127.001849"},{"BLDN_ID":"0155","BLDN_NM":"\xeb\x8f\x99\xeb\x8c\x80\xeb\xac\xb8","ROUTE":"1\xed\x98\xb8\xec\x84\xa0","LAT":"37.571687","LOT":"127.01093"},{"BLDN_ID":"0156","BLDN_NM":"\xec\x8b\xa0\xec\x84\xa4\xeb\x8f\x99","ROUTE":"1\xed\x98\xb8\xec\x84\xa0","LAT":"37.576048","LOT":"127.024634"},{"BLDN_ID":"0157","BLDN_NM":"\xec\xa0\x9c\xea\xb8\xb0\xeb\x8f\x99","ROUTE":"1\xed\x98\xb8\xec\x84\xa0","LAT":"37.578103","LOT":"127.034893"},{"BLDN_ID":"0158","BLDN_NM":"\xec\xb2\xad\xeb\x9f\x89\xeb\xa6\xac(\xec\x84\x9c\xec\x9a\xb8\xec\x8b\x9c\xeb\xa6\xbd\xeb\x8c\x80\xec\x9e\x85\xea\xb5\xac)","ROUTE":"1\xed\x98\xb8\xec\x84\xa0","LAT":"37.579956","LOT":"127.044585"},{"BLDN_ID":"0159","BLDN_NM":"\xeb\x8f\x99\xeb\xac\x98\xec\x95\x9e","ROUTE":"1\xed\x98\xb8\xec\x84\xa0","LAT":"37.573197","LOT":"127.01648"},{"BLDN_ID":"0201","BLDN_NM":"\xec\x8b\x9c\xec\xb2\xad","ROUTE":"2\xed\x98\xb8\xec\x84\xa0","LAT":"37.563588","LOT":"126.975411"},{"BLDN_ID":"0202","BLDN_NM":"\xec\x9d\x84\xec\xa7\x80\xeb\xa1\x9c\xec\x9e\x85\xea\xb5\xac","ROUTE":"2\xed\x98\xb8\xec\x84\xa0","LAT":"37.566014","LOT":"126.982618"},{"BLDN_ID":"0203","BLDN_NM":"\xec\x9d\x84\xec\xa7\x80\xeb\xa1\x9c3\xea\xb0\x80","ROUTE":"2\xed\x98\xb8\xec\x84\xa0","LAT":"37.566306","LOT":"126.991696"},{"BLDN_ID":"0204","BLDN_NM":"\xec\x9d\x84\xec\xa7\x80\xeb\xa1\x9c4\xea\xb0\x80","ROUTE":"2\xed\x98\xb8\xec\x84\xa0","LAT":"37.566595","LOT":"126.997817"},{"BLDN_ID":"0205","BLDN_NM":"\xeb\x8f\x99\xeb\x8c\x80\xeb\xac\xb8\xec\x97\xad\xec\x82\xac\xeb\xac\xb8\xed\x99\x94\xea\xb3\xb5\xec\x9b\x90","ROUTE":"2\xed\x98\xb8\xec\x84\xa0","LAT":"37.565613","LOT":"127.009054"},{"BLDN_ID":"0206","BLDN_NM":"\xec\x8b\xa0\xeb\x8b\xb9","ROUTE":"2\xed\x98\xb8\xec\x84\xa0","LAT":"37.56564","LOT":"127.019614"},{"BLDN_ID":"0207","BLDN_NM":"\xec\x83\x81\xec\x99\x95\xec\x8b\xad\xeb\xa6\xac","ROUTE":"2\xed\x98\xb8\xec\x84\xa0","LAT":"37.564354","LOT":"127.029354"},{"BLDN_ID":"0208","BLDN_NM":"\xec\x99\x95\xec\x8b\xad\xeb\xa6\xac(\xec\x84\xb1\xeb\x8f\x99\xea\xb5\xac\xec\xb2\xad)","ROUTE":"2\xed\x98\xb8\xec\x84\xa0","LAT":"37.561238","LOT":"127.036954"},{"BLDN_ID":"0209","BLDN_NM":"\xed\x95\x9c\xec\x96\x91\xeb\x8c\x80","ROUTE":"2\xed\x98\xb8\xec\x84\xa0","LAT":"37.555273","LOT":"127.043655"},{"BLDN_ID":"0210","BLDN_NM":"\xeb\x9a\x9d\xec\x84\xac","ROUTE":"2\xed\x98\xb8\xec\x84\xa0","LAT":"37.547184","LOT":"127.047367"},{"BLDN_ID":"0211","BLDN_NM":"\xec\x84\xb1\xec\x88\x98","ROUTE":"2\xed\x98\xb8\xec\x84\xa0","LAT":"37.544581","LOT":"127.055961"},{"BLDN_ID":"0212","BLDN_NM":"\xea\xb1\xb4\xeb\x8c\x80\xec\x9e\x85\xea\xb5\xac","ROUTE":"2\xed\x98\xb8\xec\x84\xa0","LAT":"37.540373","LOT":"127.069191"},{"BLDN_ID":"0213","BLDN_NM":"\xea\xb5\xac\xec\x9d\x98(\xea\xb4\x91\xec\xa7\x84\xea\xb5\xac\xec\xb2\xad)","ROUTE":"2\xed\x98\xb8\xec\x84\xa0","LAT":"37.537077","LOT":"127.085916"},{"BLDN_ID":"0214","BLDN_NM":"\xea\xb0\x95\xeb\xb3\x80(\xeb\x8f\x99\xec\x84\x9c\xec\x9a\xb8\xed\x84\xb0\xeb\xaf\xb8\xeb\x84\x90)","ROUTE":"2\xed\x98\xb8\xec\x84\xa0","LAT":"37.535095","LOT":"127.094681"},{"BLDN_ID":"0215","BLDN_NM":"\xec\x9e\xa0\xec\x8b\xa4\xeb\x82\x98\xeb\xa3\xa8","ROUTE":"2\xed\x98\xb8\xec\x84\xa0","LAT":"37.520733","LOT":"127.10379"},{"BLDN_ID":"0216","BLDN_NM":"\xec\x9e\xa0\xec\x8b\xa4(\xec\x86\xa1\xed\x8c\x8c\xea\xb5\xac\xec\xb2\xad)","ROUTE":"2\xed\x98\xb8\xec\x84\xa0","LAT":"37.513262","LOT":"127.100159"},{"BLDN_ID":"0217","BLDN_NM":"\xec\x9e\xa0\xec\x8b\xa4\xec\x83\x88\xeb\x82\xb4","ROUTE":"2\xed\x98\xb8\xec\x84\xa0","LAT":"37.511687","LOT":"127.086162"},{"BLDN_ID":"0218","BLDN_NM":"\xec\xa2\x85\xed\x95\xa9\xec\x9a\xb4\xeb\x8f\x99\xec\x9e\xa5","ROUTE":"2\xed\x98\xb8\xec\x84\xa0","LAT":"37.511022","LOT":"127.073704"},{"BLDN_ID":"0219","BLDN_NM":"\xec\x82\xbc\xec\x84\xb1(\xeb\xac\xb4\xec\x97\xad\xec\x84\xbc\xed\x84\xb0)","ROUTE":"2\xed\x98\xb8\xec\x84\xa0","LAT":"37.508844","LOT":"127.06316"},{"BLDN_ID":"0220","BLDN_NM":"\xec\x84\xa0\xeb\xa6\x89","ROUTE":"2\xed\x98\xb8\xec\x84\xa0","LAT":"37.504286","LOT":"127.048203"},{"BLDN_ID":"0221","BLDN_NM":"\xec\x97\xad\xec\x82\xbc","ROUTE":"2\xed\x98\xb8\xec\x84\xa0","LAT":"37.500622","LOT":"127.036456"},{"BLDN_ID":"0222","BLDN_NM":"\xea\xb0\x95\xeb\x82\xa8","ROUTE":"2\xed\x98\xb8\xec\x84\xa0","LAT":"37.49799","LOT":"127.027912"},{"BLDN_ID":"0223","BLDN_NM":"\xea\xb5\x90\xeb\x8c\x80(\xeb\xb2\x95\xec\x9b\x90.\xea\xb2\x80\xec\xb0\xb0\xec\xb2\xad)","ROUTE":"2\xed\x98\xb8\xec\x84\xa0","LAT":"37.493961","LOT":"127.014667"},{"BLDN_ID":"0224","BLDN_NM":"\xec\x84\x9c\xec\xb4\x88","ROUTE":"2\xed\x98\xb8\xec\x84\xa0","LAT":"37.491897","LOT":"127.007917"},{"BLDN_ID":"0225","BLDN_NM":"\xeb\xb0\xa9\xeb\xb0\xb0","ROUTE":"2\xed\x98\xb8\xec\x84\xa0","LAT":"37.481426","LOT":"126.997596"},{"BLDN_ID":"0226","BLDN_NM":"\xec\x82\xac\xeb\x8b\xb9","ROUTE":"2\xed\x98\xb8\xec\x84\xa0","LAT":"37.476538","LOT":"126.981544"},{"BLDN_ID":"0227","BLDN_NM":"\xeb\x82\x99\xec\x84\xb1\xeb\x8c\x80","ROUTE":"2\xed\x98\xb8\xec\x84\xa0","LAT":"37.47693","LOT":"126.963693"},{"BLDN_ID":"0228","BLDN_NM":"\xec\x84\x9c\xec\x9a\xb8\xeb\x8c\x80\xec\x9e\x85\xea\xb5\xac(\xea\xb4\x80\xec\x95\x85\xea\xb5\xac\xec\xb2\xad)","ROUTE":"2\xed\x98\xb8\xec\x84\xa0","LAT":"37.481247","LOT":"126.952739"},{"BLDN_ID":"0229","BLDN_NM":"\xeb\xb4\x89\xec\xb2\x9c","ROUTE":"2\xed\x98\xb8\xec\x84\xa0","LAT":"37.482362","LOT":"126.941892"},{"BLDN_ID":"0230","BLDN_NM":"\xec\x8b\xa0\xeb\xa6\xbc","ROUTE":"2\xed\x98\xb8\xec\x84\xa0","LAT":"37.484201","LOT":"126.929715"},{"BLDN_ID":"0231","BLDN_NM":"\xec\x8b\xa0\xeb\x8c\x80\xeb\xb0\xa9","ROUTE":"2\xed\x98\xb8\xec\x84\xa0","LAT":"37.487462","LOT":"126.913149"},{"BLDN_ID":"0232","BLDN_NM":"\xea\xb5\xac\xeb\xa1\x9c\xeb\x94\x94\xec\xa7\x80\xed\x84\xb8\xeb\x8b\xa8\xec\xa7\x80","ROUTE":"2\xed\x98\xb8\xec\x84\xa0","LAT":"37.485266","LOT":"126.901401"},{"BLDN_ID":"0233","BLDN_NM":"\xeb\x8c\x80\xeb\xa6\xbc(\xea\xb5\xac\xeb\xa1\x9c\xea\xb5\xac\xec\xb2\xad)","ROUTE":"2\xed\x98\xb8\xec\x84\xa0","LAT":"37.493243","LOT":"126.894932"},{"BLDN_ID":"0234","BLDN_NM":"\xec\x8b\xa0\xeb\x8f\x84\xeb\xa6\xbc","ROUTE":"2\xed\x98\xb8\xec\x84\xa0","LAT":"37.508961","LOT":"126.891084"},{"BLDN_ID":"0235","BLDN_NM":"\xeb\xac\xb8\xeb\x9e\x98","ROUTE":"2\xed\x98\xb8\xec\x84\xa0","LAT":"37.517933","LOT":"126.89476"},{"BLDN_ID":"0236","BLDN_NM":"\xec\x98\x81\xeb\x93\xb1\xed\x8f\xac\xea\xb5\xac\xec\xb2\xad","ROUTE":"2\xed\x98\xb8\xec\x84\xa0","LAT":"37.525706","LOT":"126.89661"},{"BLDN_ID":"0237","BLDN_NM":"\xeb\x8b\xb9\xec\x82\xb0","ROUTE":"2\xed\x98\xb8\xec\x84\xa0","LAT":"37.534946","LOT":"126.902767"},{"BLDN_ID":"0238","BLDN_NM":"\xed\x95\xa9\xec\xa0\x95","ROUTE":"2\xed\x98\xb8\xec\x84\xa0","LAT":"37.549457","LOT":"126.913808"},{"BLDN_ID":"0239","BLDN_NM":"\xed\x99\x8d\xeb\x8c\x80\xec\x9e\x85\xea\xb5\xac","ROUTE":"2\xed\x98\xb8\xec\x84\xa0","LAT":"37.55679","LOT":"126.923708"},{"BLDN_ID":"0240","BLDN_NM":"\xec\x8b\xa0\xec\xb4\x8c","ROUTE":"2\xed\x98\xb8\xec\x84\xa0","LAT":"37.555131","LOT":"126.936926"},{"BLDN_ID":"0241","BLDN_NM":"\xec\x9d\xb4\xeb\x8c\x80","ROUTE":"2\xed\x98\xb8\xec\x84\xa0","LAT":"37.556733","LOT":"126.946013"},{"BLDN_ID":"0242","BLDN_NM":"\xec\x95\x84\xed\x98\x84","ROUTE":"2\xed\x98\xb8\xec\x84\xa0","LAT":"37.557345","LOT":"126.956141"},{"BLDN_ID":"0243","BLDN_NM":"\xec\xb6\xa9\xec\xa0\x95\xeb\xa1\x9c(\xea\xb2\xbd\xea\xb8\xb0\xeb\x8c\x80\xec\x9e\x85\xea\xb5\xac)","ROUTE":"2\xed\x98\xb8\xec\x84\xa0","LAT":"37.559704","LOT":"126.964378"},{"BLDN_ID":"0244","BLDN_NM":"\xec\x9a\xa9\xeb\x8b\xb5","ROUTE":"2\xed\x98\xb8\xec\x84\xa0","LAT":"37.561904","LOT":"127.050899"},{"BLDN_ID":"0245","BLDN_NM":"\xec\x8b\xa0\xeb\x8b\xb5","ROUTE":"2\xed\x98\xb8\xec\x84\xa0","LAT":"37.57004","LOT":"127.046481"},{"BLDN_ID":"0246","BLDN_NM":"\xec\x8b\xa0\xec\x84\xa4\xeb\x8f\x99","ROUTE":"2\xed\x98\xb8\xec\x84\xa0","LAT":"37.574747","LOT":"127.024932"},{"BLDN_ID":"0247","BLDN_NM":"\xeb\x8f\x84\xeb\xa6\xbc\xec\xb2\x9c","ROUTE":"2\xed\x98\xb8\xec\x84\xa0","LAT":"37.514287","LOT":"126.882768"},{"BLDN_ID":"0248","BLDN_NM":"\xec\x96\x91\xec\xb2\x9c\xea\xb5\xac\xec\xb2\xad","ROUTE":"2\xed\x98\xb8\xec\x84\xa0","LAT":"37.512398","LOT":"126.865819"},{"BLDN_ID":"0249","BLDN_NM":"\xec\x8b\xa0\xec\xa0\x95\xeb\x84\xa4\xea\xb1\xb0\xeb\xa6\xac","ROUTE":"2\xed\x98\xb8\xec\x84\xa0","LAT":"37.520074","LOT":"126.852912"},{"BLDN_ID":"0250","BLDN_NM":"\xec\x9a\xa9\xeb\x91\x90(\xeb\x8f\x99\xeb\x8c\x80\xeb\xac\xb8\xea\xb5\xac\xec\xb2\xad)","ROUTE":"2\xed\x98\xb8\xec\x84\xa0","LAT":"37.574028","LOT":"127.038091"},{"BLDN_ID":"0309","BLDN_NM":"\xec\xa7\x80\xec\xb6\x95","ROUTE":"3\xed\x98\xb8\xec\x84\xa0","LAT":"37.648033","LOT":"126.913917"},{"BLDN_ID":"0310","BLDN_NM":"\xea\xb5\xac\xed\x8c\x8c\xeb\xb0\x9c","ROUTE":"3\xed\x98\xb8\xec\x84\xa0","LAT":"37.636763","LOT":"126.918821"},{"BLDN_ID":"0311","BLDN_NM":"\xec\x97\xb0\xec\x8b\xa0\xeb\x82\xb4","ROUTE":"3\xed\x98\xb8\xec\x84\xa0","LAT":"37.619229","LOT":"126.921038"},{"BLDN_ID":"0312","BLDN_NM":"\xeb\xb6\x88\xea\xb4\x91","ROUTE":"3\xed\x98\xb8\xec\x84\xa0","LAT":"37.610553","LOT":"126.92982"},{"BLDN_ID":"0313","BLDN_NM":"\xeb\x85\xb9\xeb\xb2\x88","ROUTE":"3\xed\x98\xb8\xec\x84\xa0","LAT":"37.600927","LOT":"126.935756"},{"BLDN_ID":"0314","BLDN_NM":"\xed\x99\x8d\xec\xa0\x9c","ROUTE":"3\xed\x98\xb8\xec\x84\xa0","LAT":"37.589066","LOT":"126.943736"},{"BLDN_ID":"0315","BLDN_NM":"\xeb\xac\xb4\xec\x95\x85\xec\x9e\xac","ROUTE":"3\xed\x98\xb8\xec\x84\xa0","LAT":"37.582299","LOT":"126.950291"},{"BLDN_ID":"0316","BLDN_NM":"\xeb\x8f\x85\xeb\xa6\xbd\xeb\xac\xb8","ROUTE":"3\xed\x98\xb8\xec\x84\xa0","LAT":"37.574571","LOT":"126.957748"},{"BLDN_ID":"0317","BLDN_NM":"\xea\xb2\xbd\xeb\xb3\xb5\xea\xb6\x81(\xec\xa0\x95\xeb\xb6\x80\xec\x84\x9c\xec\x9a\xb8\xec\xb2\xad\xec\x82\xac)","ROUTE":"3\xed\x98\xb8\xec\x84\xa0","LAT":"37.575762","LOT":"126.97353"},{"BLDN_ID":"0318","BLDN_NM":"\xec\x95\x88\xea\xb5\xad","ROUTE":"3\xed\x98\xb8\xec\x84\xa0","LAT":"37.576477","LOT":"126.985443"},{"BLDN_ID":"0319","BLDN_NM":"\xec\xa2\x85\xeb\xa1\x9c3\xea\xb0\x80","ROUTE":"3\xed\x98\xb8\xec\x84\xa0","LAT":"37.571605","LOT":"126.991791"},{"BLDN_ID":"0320","BLDN_NM":"\xec\x9d\x84\xec\xa7\x80\xeb\xa1\x9c3\xea\xb0\x80","ROUTE":"3\xed\x98\xb8\xec\x84\xa0","LAT":"37.566672","LOT":"126.992548"},{"BLDN_ID":"0321","BLDN_NM":"\xec\xb6\xa9\xeb\xac\xb4\xeb\xa1\x9c","ROUTE":"3\xed\x98\xb8\xec\x84\xa0","LAT":"37.56143","LOT":"126.994072"},{"BLDN_ID":"0322","BLDN_NM":"\xeb\x8f\x99\xeb\x8c\x80\xec\x9e\x85\xea\xb5\xac","ROUTE":"3\xed\x98\xb8\xec\x84\xa0","LAT":"37.559052","LOT":"127.005602"},{"BLDN_ID":"0323","BLDN_NM":"\xec\x95\xbd\xec\x88\x98","ROUTE":"3\xed\x98\xb8\xec\x84\xa0","LAT":"37.554867","LOT":"127.010541"},{"BLDN_ID":"0324","BLDN_NM":"\xea\xb8\x88\xed\x98\xb8","ROUTE":"3\xed\x98\xb8\xec\x84\xa0","LAT":"37.548034","LOT":"127.015872"},{"BLDN_ID":"0325","BLDN_NM":"\xec\x98\xa5\xec\x88\x98","ROUTE":"3\xed\x98\xb8\xec\x84\xa0","LAT":"37.541684","LOT":"127.017269"},{"BLDN_ID":"0326","BLDN_NM":"\xec\x95\x95\xea\xb5\xac\xec\xa0\x95","ROUTE":"3\xed\x98\xb8\xec\x84\xa0","LAT":"37.527072","LOT":"127.028461"},{"BLDN_ID":"0327","BLDN_NM":"\xec\x8b\xa0\xec\x82\xac","ROUTE":"3\xed\x98\xb8\xec\x84\xa0","LAT":"37.516334","LOT":"127.020114"},{"BLDN_ID":"0328","BLDN_NM":"\xec\x9e\xa0\xec\x9b\x90","ROUTE":"3\xed\x98\xb8\xec\x84\xa0","LAT":"37.512759","LOT":"127.01122"},{"BLDN_ID":"0329","BLDN_NM":"\xea\xb3\xa0\xec\x86\x8d\xed\x84\xb0\xeb\xaf\xb8\xeb\x84\x90","ROUTE":"3\xed\x98\xb8\xec\x84\xa0","LAT":"37.504891","LOT":"127.004916"},{"BLDN_ID":"0330","BLDN_NM":"\xea\xb5\x90\xeb\x8c\x80(\xeb\xb2\x95\xec\x9b\x90.\xea\xb2\x80\xec\xb0\xb0\xec\xb2\xad)","ROUTE":"3\xed\x98\xb8\xec\x84\xa0","LAT":"37.493025","LOT":"127.013786"},{"BLDN_ID":"0331","BLDN_NM":"\xeb\x82\xa8\xeb\xb6\x80\xed\x84\xb0\xeb\xaf\xb8\xeb\x84\x90(\xec\x98\x88\xec\x88\xa0\xec\x9d\x98\xec\xa0\x84\xeb\x8b\xb9)","ROUTE":"3\xed\x98\xb8\xec\x84\xa0","LAT":"37.485013","LOT":"127.016189"},{"BLDN_ID":"0332","BLDN_NM":"\xec\x96\x91\xec\x9e\xac(\xec\x84\x9c\xec\xb4\x88\xea\xb5\xac\xec\xb2\xad)","ROUTE":"3\xed\x98\xb8\xec\x84\xa0","LAT":"37.484477","LOT":"127.033902"},{"BLDN_ID":"0333","BLDN_NM":"\xeb\xa7\xa4\xeb\xb4\x89","ROUTE":"3\xed\x98\xb8\xec\x84\xa0","LAT":"37.486947","LOT":"127.046769"},{"BLDN_ID":"0334","BLDN_NM":"\xeb\x8f\x84\xea\xb3\xa1","ROUTE":"3\xed\x98\xb8\xec\x84\xa0","LAT":"37.490922","LOT":"127.055452"},{"BLDN_ID":"0335","BLDN_NM":"\xeb\x8c\x80\xec\xb9\x98","ROUTE":"3\xed\x98\xb8\xec\x84\xa0","LAT":"37.494612","LOT":"127.063642"},{"BLDN_ID":"0336","BLDN_NM":"\xed\x95\x99\xec\x97\xac\xec\x9a\xb8","ROUTE":"3\xed\x98\xb8\xec\x84\xa0","LAT":"37.496663","LOT":"127.070594"},{"BLDN_ID":"0337","BLDN_NM":"\xeb\x8c\x80\xec\xb2\xad","ROUTE":"3\xed\x98\xb8\xec\x84\xa0","LAT":"37.493514","LOT":"127.079532"},{"BLDN_ID":"0338","BLDN_NM":"\xec\x9d\xbc\xec\x9b\x90","ROUTE":"3\xed\x98\xb8\xec\x84\xa0","LAT":"37.483681","LOT":"127.08439"},{"BLDN_ID":"0339","BLDN_NM":"\xec\x88\x98\xec\x84\x9c","ROUTE":"3\xed\x98\xb8\xec\x84\xa0","LAT":"37.487378","LOT":"127.101907"},{"BLDN_ID":"0340","BLDN_NM":"\xea\xb0\x80\xeb\x9d\xbd\xec\x8b\x9c\xec\x9e\xa5","ROUTE":"3\xed\x98\xb8\xec\x84\xa0","LAT":"37.492245","LOT":"127.117757"},{"BLDN_ID":"0341","BLDN_NM":"\xea\xb2\xbd\xec\xb0\xb0\xeb\xb3\x91\xec\x9b\x90","ROUTE":"3\xed\x98\xb8\xec\x84\xa0","LAT":"37.495918","LOT":"127.12454"},{"BLDN_ID":"0342","BLDN_NM":"\xec\x98\xa4\xea\xb8\x88","ROUTE":"3\xed\x98\xb8\xec\x84\xa0","LAT":"37.502129","LOT":"127.128319"},{"BLDN_ID":"0405","BLDN_NM":"\xec\xa7\x84\xec\xa0\x91","ROUTE":"\xec\xa7\x84\xec\xa0\x91\xec\x84\xa0","LAT":"37.7205","LOT":"127.2034"},{"BLDN_ID":"0406","BLDN_NM":"\xec\x98\xa4\xeb\x82\xa8","ROUTE":"\xec\xa7\x84\xec\xa0\x91\xec\x84\xa0","LAT":"37.705","LOT":"127.19281"},{"BLDN_ID":"0408","BLDN_NM":"\xeb\xb3\x84\xeb\x82\xb4\xeb\xb3\x84\xea\xb0\x80\xeb\x9e\x8c","ROUTE":"\xec\xa7\x84\xec\xa0\x91\xec\x84\xa0","LAT":"37.66778","LOT":"127.11581"},{"BLDN_ID":"0409","BLDN_NM":"\xeb\x8b\xb9\xea\xb3\xa0\xea\xb0\x9c","ROUTE":"4\xed\x98\xb8\xec\x84\xa0","LAT":"37.670272","LOT":"127.079066"},{"BLDN_ID":"0410","BLDN_NM":"\xec\x83\x81\xea\xb3\x84","ROUTE":"4\xed\x98\xb8\xec\x84\xa0","LAT":"37.660878","LOT":"127.073572"},{"BLDN_ID":"0411","BLDN_NM":"\xeb\x85\xb8\xec\x9b\x90","ROUTE":"4\xed\x98\xb8\xec\x84\xa0","LAT":"37.65627","LOT":"127.063276"},{"BLDN_ID":"0412","BLDN_NM":"\xec\xb0\xbd\xeb\x8f\x99","ROUTE":"4\xed\x98\xb8\xec\x84\xa0","LAT":"37.653088","LOT":"127.047274"},{"BLDN_ID":"0413","BLDN_NM":"\xec\x8c\x8d\xeb\xac\xb8","ROUTE":"4\xed\x98\xb8\xec\x84\xa0","LAT":"37.648627","LOT":"127.034709"},{"BLDN_ID":"0414","BLDN_NM":"\xec\x88\x98\xec\x9c\xa0(\xea\xb0\x95\xeb\xb6\x81\xea\xb5\xac\xec\xb2\xad)","ROUTE":"4\xed\x98\xb8\xec\x84\xa0","LAT":"37.638052","LOT":"127.025732"},{"BLDN_ID":"0415","BLDN_NM":"\xeb\xaf\xb8\xec\x95\x84(\xec\x84\x9c\xec\x9a\xb8\xec\x82\xac\xec\x9d\xb4\xeb\xb2\x84\xeb\x8c\x80\xed\x95\x99)","ROUTE":"4\xed\x98\xb8\xec\x84\xa0","LAT":"37.62667","LOT":"127.025983"},{"BLDN_ID":"0416","BLDN_NM":"\xeb\xaf\xb8\xec\x95\x84\xec\x82\xac\xea\xb1\xb0\xeb\xa6\xac","ROUTE":"4\xed\x98\xb8\xec\x84\xa0","LAT":"37.613292","LOT":"127.030053"},{"BLDN_ID":"0417","BLDN_NM":"\xea\xb8\xb8\xec\x9d\x8c","ROUTE":"4\xed\x98\xb8\xec\x84\xa0","LAT":"37.603407","LOT":"127.025053"},{"BLDN_ID":"0418","BLDN_NM":"\xec\x84\xb1\xec\x8b\xa0\xec\x97\xac\xeb\x8c\x80\xec\x9e\x85\xea\xb5\xac(\xeb\x8f\x88\xec\x95\x94)","ROUTE":"4\xed\x98\xb8\xec\x84\xa0","LAT":"37.592612","LOT":"127.016441"},{"BLDN_ID":"0419","BLDN_NM":"\xed\x95\x9c\xec\x84\xb1\xeb\x8c\x80\xec\x9e\x85\xea\xb5\xac(\xec\x82\xbc\xec\x84\xa0\xea\xb5\x90)","ROUTE":"4\xed\x98\xb8\xec\x84\xa0","LAT":"37.588458","LOT":"127.006221"},{"BLDN_ID":"0420","BLDN_NM":"\xed\x98\x9c\xed\x99\x94","ROUTE":"4\xed\x98\xb8\xec\x84\xa0","LAT":"37.582336","LOT":"127.001844"},{"BLDN_ID":"0421","BLDN_NM":"\xeb\x8f\x99\xeb\x8c\x80\xeb\xac\xb8","ROUTE":"4\xed\x98\xb8\xec\x84\xa0","LAT":"37.57093","LOT":"127.009287"},{"BLDN_ID":"0422","BLDN_NM":"\xeb\x8f\x99\xeb\x8c\x80\xeb\xac\xb8\xec\x97\xad\xec\x82\xac\xeb\xac\xb8\xed\x99\x94\xea\xb3\xb5\xec\x9b\x90","ROUTE":"4\xed\x98\xb8\xec\x84\xa0","LAT":"37.565133","LOT":"127.007885"},{"BLDN_ID":"0423","BLDN_NM":"\xec\xb6\xa9\xeb\xac\xb4\xeb\xa1\x9c","ROUTE":"4\xed\x98\xb8\xec\x84\xa0","LAT":"37.561207","LOT":"126.99408"},{"BLDN_ID":"0424","BLDN_NM":"\xeb\xaa\x85\xeb\x8f\x99","ROUTE":"4\xed\x98\xb8\xec\x84\xa0","LAT":"37.560989","LOT":"126.986325"},{"BLDN_ID":"0425","BLDN_NM":"\xed\x9a\x8c\xed\x98\x84(\xeb\x82\xa8\xeb\x8c\x80\xeb\xac\xb8\xec\x8b\x9c\xec\x9e\xa5)","ROUTE":"4\xed\x98\xb8\xec\x84\xa0","LAT":"37.558514","LOT":"126.978246"},{"BLDN_ID":"0426","BLDN_NM":"\xec\x84\x9c\xec\x9a\xb8\xec\x97\xad","ROUTE":"4\xed\x98\xb8\xec\x84\xa0","LAT":"37.55281","LOT":"126.972556"},{"BLDN_ID":"0427","BLDN_NM":"\xec\x88\x99\xeb\x8c\x80\xec\x9e\x85\xea\xb5\xac(\xea\xb0\x88\xec\x9b\x94)","ROUTE":"4\xed\x98\xb8\xec\x84\xa0","LAT":"37.54456","LOT":"126.972106"},{"BLDN_ID":"0428","BLDN_NM":"\xec\x82\xbc\xea\xb0\x81\xec\xa7\x80","ROUTE":"4\xed\x98\xb8\xec\x84\xa0","LAT":"37.534075","LOT":"126.9726"},{"BLDN_ID":"0429","BLDN_NM":"\xec\x8b\xa0\xec\x9a\xa9\xec\x82\xb0","ROUTE":"4\xed\x98\xb8\xec\x84\xa0","LAT":"37.52917","LOT":"126.967894"},{"BLDN_ID":"0430","BLDN_NM":"\xec\x9d\xb4\xec\xb4\x8c(\xea\xb5\xad\xeb\xa6\xbd\xec\xa4\x91\xec\x95\x99\xeb\xb0\x95\xeb\xac\xbc\xea\xb4\x80)","ROUTE":"4\xed\x98\xb8\xec\x84\xa0","LAT":"37.522295","LOT":"126.974733"},{"BLDN_ID":"0431","BLDN_NM":"\xeb\x8f\x99\xec\x9e\x91(\xed\x98\x84\xec\xb6\xa9\xec\x9b\x90)","ROUTE":"4\xed\x98\xb8\xec\x84\xa0","LAT":"37.502852","LOT":"126.980347"},{"BLDN_ID":"0432","BLDN_NM":"\xec\xb4\x9d\xec\x8b\xa0\xeb\x8c\x80\xec\x9e\x85\xea\xb5\xac(\xec\x9d\xb4\xec\x88\x98)","ROUTE":"4\xed\x98\xb8\xec\x84\xa0","LAT":"37.486263","LOT":"126.981989"},{"BLDN_ID":"0433","BLDN_NM":"\xec\x82\xac\xeb\x8b\xb9","ROUTE":"4\xed\x98\xb8\xec\x84\xa0","LAT":"37.476955","LOT":"126.981651"},{"BLDN_ID":"0434","BLDN_NM":"\xeb\x82\xa8\xed\x83\x9c\xeb\xa0\xb9","ROUTE":"4\xed\x98\xb8\xec\x84\xa0","LAT":"37.463873","LOT":"126.989134"},{"BLDN_ID":"1001","BLDN_NM":"\xec\x84\x9c\xec\x9a\xb8\xec\x97\xad","ROUTE":"\xea\xb2\xbd\xeb\xb6\x80\xec\x84\xa0","LAT":"37.554337","LOT":"126.971134"},{"BLDN_ID":"1002","BLDN_NM":"\xeb\x82\xa8\xec\x98\x81","ROUTE":"\xea\xb2\xbd\xeb\xb6\x80\xec\x84\xa0","LAT":"37.541021","LOT":"126.9713"},{"BLDN_ID":"1003","BLDN_NM":"\xec\x9a\xa9\xec\x82\xb0","ROUTE":"\xea\xb2\xbd\xeb\xb6\x80\xec\x84\xa0","LAT":"37.529849","LOT":"126.964561"},{"BLDN_ID":"1004","BLDN_NM":"\xeb\x85\xb8\xeb\x9f\x89\xec\xa7\x84","ROUTE":"\xea\xb2\xbd\xeb\xb6\x80\xec\x84\xa0","LAT":"37.514149","LOT":"126.94271"},{"BLDN_ID":"1005","BLDN_NM":"\xeb\x8c\x80\xeb\xb0\xa9","ROUTE":"\xea\xb2\xbd\xeb\xb6\x80\xec\x84\xa0","LAT":"37.513342","LOT":"126.926382"},{"BLDN_ID":"1006","BLDN_NM":"\xec\x98\x81\xeb\x93\xb1\xed\x8f\xac","ROUTE":"\xea\xb2\xbd\xeb\xb6\x80\xec\x84\xa0","LAT":"37.515504","LOT":"126.907628"},{"BLDN_ID":"1007","BLDN_NM":"\xec\x8b\xa0\xeb\x8f\x84\xeb\xa6\xbc","ROUTE":"\xea\xb2\xbd\xeb\xb6\x80\xec\x84\xa0","LAT":"37.508787","LOT":"126.891144"},{"BLDN_ID":"1008","BLDN_NM":"\xec\x9d\xb4\xec\xb4\x8c(\xea\xb5\xad\xeb\xa6\xbd\xec\xa4\x91\xec\x95\x99\xeb\xb0\x95\xeb\xac\xbc\xea\xb4\x80)","ROUTE":"\xea\xb2\xbd\xec\x9b\x90\xec\x84\xa0","LAT":"3

In [18]:
data = m.json()
data

{'subwayStationMaster': {'list_total_count': 909,
  'RESULT': {'CODE': 'INFO-000', 'MESSAGE': '정상 처리되었습니다'},
  'row': [{'BLDN_ID': '0150',
    'BLDN_NM': '서울역',
    'ROUTE': '1호선',
    'LAT': '37.556228',
    'LOT': '126.972135'},
   {'BLDN_ID': '0151',
    'BLDN_NM': '시청',
    'ROUTE': '1호선',
    'LAT': '37.565715',
    'LOT': '126.977088'},
   {'BLDN_ID': '0152',
    'BLDN_NM': '종각',
    'ROUTE': '1호선',
    'LAT': '37.570161',
    'LOT': '126.982923'},
   {'BLDN_ID': '0153',
    'BLDN_NM': '종로3가',
    'ROUTE': '1호선',
    'LAT': '37.570406',
    'LOT': '126.991847'},
   {'BLDN_ID': '0154',
    'BLDN_NM': '종로5가',
    'ROUTE': '1호선',
    'LAT': '37.570926',
    'LOT': '127.001849'},
   {'BLDN_ID': '0155',
    'BLDN_NM': '동대문',
    'ROUTE': '1호선',
    'LAT': '37.571687',
    'LOT': '127.01093'},
   {'BLDN_ID': '0156',
    'BLDN_NM': '신설동',
    'ROUTE': '1호선',
    'LAT': '37.576048',
    'LOT': '127.024634'},
   {'BLDN_ID': '0157',
    'BLDN_NM': '제기동',
    'ROUTE': '1호선',
    'LAT': '37.578103',
    'LOT': '127.034893'},
   {'BLDN_ID': '0158',
    'BLDN_NM': '청량리(서울시립대입구)',
    'ROUTE': '1호선',
    'LAT': '37.579956',
    'LOT': '127.044585'},
   {'BLDN_ID': '0159',
    'BLDN_NM': '동묘앞',
    'ROUTE': '1호선',
    'LAT': '37.573197',
    'LOT': '127.01648'},
   {'BLDN_ID': '0201',
    'BLDN_NM': '시청',
    'ROUTE': '2호선',
    'LAT': '37.563588',
    'LOT': '126.975411'},
   {'BLDN_ID': '0202',
    'BLDN_NM': '을지로입구',
    'ROUTE': '2호선',
    'LAT': '37.566014',
    'LOT': '126.982618'},
   {'BLDN_ID': '0203',
    'BLDN_NM': '을지로3가',
    'ROUTE': '2호선',
    'LAT': '37.566306',
    'LOT': '126.991696'},
   {'BLDN_ID': '0204',
    'BLDN_NM': '을지로4가',
    'ROUTE': '2호선',
    'LAT': '37.566595',
    'LOT': '126.997817'},
   {'BLDN_ID': '0205',
    'BLDN_NM': '동대문역사문화공원',
    'ROUTE': '2호선',
    'LAT': '37.565613',
    'LOT': '127.009054'},
   {'BLDN_ID': '0206',
    'BLDN_NM': '신당',
    'ROUTE': '2호선',
    'LAT': '37.56564',
    'LOT': '127.019614'},
   {'BLDN_ID': '0207',
    'BLDN_NM': '상왕십리',
    'ROUTE': '2호선',
    'LAT': '37.564354',
    'LOT': '127.029354'},
   {'BLDN_ID': '0208',
    'BLDN_NM': '왕십리(성동구청)',
    'ROUTE': '2호선',
    'LAT': '37.561238',
    'LOT': '127.036954'},
   {'BLDN_ID': '0209',
    'BLDN_NM': '한양대',
    'ROUTE': '2호선',
    'LAT': '37.555273',
    'LOT': '127.043655'},
   {'BLDN_ID': '0210',
    'BLDN_NM': '뚝섬',
    'ROUTE': '2호선',
    'LAT': '37.547184',
    'LOT': '127.047367'},
   {'BLDN_ID': '0211',
    'BLDN_NM': '성수',
    'ROUTE': '2호선',
    'LAT': '37.544581',
    'LOT': '127.055961'},
   {'BLDN_ID': '0212',
    'BLDN_NM': '건대입구',
    'ROUTE': '2호선',
    'LAT': '37.540373',
    'LOT': '127.069191'},
   {'BLDN_ID': '0213',
    'BLDN_NM': '구의(광진구청)',
    'ROUTE': '2호선',
    'LAT': '37.537077',
    'LOT': '127.085916'},
   {'BLDN_ID': '0214',
    'BLDN_NM': '강변(동서울터미널)',
    'ROUTE': '2호선',
    'LAT': '37.535095',
    'LOT': '127.094681'},
   {'BLDN_ID': '0215',
    'BLDN_NM': '잠실나루',
    'ROUTE': '2호선',
    'LAT': '37.520733',
    'LOT': '127.10379'},
   {'BLDN_ID': '0216',
    'BLDN_NM': '잠실(송파구청)',
    'ROUTE': '2호선',
    'LAT': '37.513262',
    'LOT': '127.100159'},
   {'BLDN_ID': '0217',
    'BLDN_NM': '잠실새내',
    'ROUTE': '2호선',
    'LAT': '37.511687',
    'LOT': '127.086162'},
   {'BLDN_ID': '0218',
    'BLDN_NM': '종합운동장',
    'ROUTE': '2호선',
    'LAT': '37.511022',
    'LOT': '127.073704'},
   {'BLDN_ID': '0219',
    'BLDN_NM': '삼성(무역센터)',
    'ROUTE': '2호선',
    'LAT': '37.508844',
    'LOT': '127.06316'},
   {'BLDN_ID': '0220',
    'BLDN_NM': '선릉',
    'ROUTE': '2호선',
    'LAT': '37.504286',
    'LOT': '127.048203'},
   {'BLDN_ID': '0221',
    'BLDN_NM': '역삼',
    'ROUTE': '2호선',
    'LAT': '37.500622',
    'LOT': '127.036456'},
   {'BLDN_ID': '0222',
    'BLDN_NM': '강남',
    'ROUTE': '2호선',
    'LAT': '37.49799',
    'LOT': '127.027912'},
   {'BLDN_ID': '0223',
    'BLDN_NM': '교대(법원.검찰청)',
    'ROUTE': '2호선',
    'LAT': '37.493961',
    'LOT': '127.014667'},
   {'BLDN_ID': '0224',
    'BLDN_NM': '서초',
    'ROUTE': '2호선',
    'LAT': '37.491897',
    'LOT': '127.007917'},
   {'BLDN_ID': '0225',
    'BLDN_NM': '방배',
    'ROUTE': '2호선',
    'LAT': '37.481426',
    'LOT': '126.997596'},
   {'BLDN_ID': '0226',
    'BLDN_NM': '사당',
    'ROUTE': '2호선',
    'LAT': '37.476538',
    'LOT': '126.981544'},
   {'BLDN_ID': '0227',
    'BLDN_NM': '낙성대',
    'ROUTE': '2호선',
    'LAT': '37.47693',
    'LOT': '126.963693'},
   {'BLDN_ID': '0228',
    'BLDN_NM': '서울대입구(관악구청)',
    'ROUTE': '2호선',
    'LAT': '37.481247',
    'LOT': '126.952739'},
   {'BLDN_ID': '0229',
    'BLDN_NM': '봉천',
    'ROUTE': '2호선',
    'LAT': '37.482362',
    'LOT': '126.941892'},
   {'BLDN_ID': '0230',
    'BLDN_NM': '신림',
    'ROUTE': '2호선',
    'LAT': '37.484201',
    'LOT': '126.929715'},
   {'BLDN_ID': '0231',
    'BLDN_NM': '신대방',
    'ROUTE': '2호선',
    'LAT': '37.487462',
    'LOT': '126.913149'},
   {'BLDN_ID': '0232',
    'BLDN_NM': '구로디지털단지',
    'ROUTE': '2호선',
    'LAT': '37.485266',
    'LOT': '126.901401'},
   {'BLDN_ID': '0233',
    'BLDN_NM': '대림(구로구청)',
    'ROUTE': '2호선',
    'LAT': '37.493243',
    'LOT': '126.894932'},
   {'BLDN_ID': '0234',
    'BLDN_NM': '신도림',
    'ROUTE': '2호선',
    'LAT': '37.508961',
    'LOT': '126.891084'},
   {'BLDN_ID': '0235',
    'BLDN_NM': '문래',
    'ROUTE': '2호선',
    'LAT': '37.517933',
    'LOT': '126.89476'},
   {'BLDN_ID': '0236',
    'BLDN_NM': '영등포구청',
    'ROUTE': '2호선',
    'LAT': '37.525706',
    'LOT': '126.89661'},
   {'BLDN_ID': '0237',
    'BLDN_NM': '당산',
    'ROUTE': '2호선',
    'LAT': '37.534946',
    'LOT': '126.902767'},
   {'BLDN_ID': '0238',
    'BLDN_NM': '합정',
    'ROUTE': '2호선',
    'LAT': '37.549457',
    'LOT': '126.913808'},
   {'BLDN_ID': '0239',
    'BLDN_NM': '홍대입구',
    'ROUTE': '2호선',
    'LAT': '37.55679',
    'LOT': '126.923708'},
   {'BLDN_ID': '0240',
    'BLDN_NM': '신촌',
    'ROUTE': '2호선',
    'LAT': '37.555131',
    'LOT': '126.936926'},
   {'BLDN_ID': '0241',
    'BLDN_NM': '이대',
    'ROUTE': '2호선',
    'LAT': '37.556733',
    'LOT': '126.946013'},
   {'BLDN_ID': '0242',
    'BLDN_NM': '아현',
    'ROUTE': '2호선',
    'LAT': '37.557345',
    'LOT': '126.956141'},
   {'BLDN_ID': '0243',
    'BLDN_NM': '충정로(경기대입구)',
    'ROUTE': '2호선',
    'LAT': '37.559704',
    'LOT': '126.964378'},
   {'BLDN_ID': '0244',
    'BLDN_NM': '용답',
    'ROUTE': '2호선',
    'LAT': '37.561904',
    'LOT': '127.050899'},
   {'BLDN_ID': '0245',
    'BLDN_NM': '신답',
    'ROUTE': '2호선',
    'LAT': '37.57004',
    'LOT': '127.046481'},
   {'BLDN_ID': '0246',
    'BLDN_NM': '신설동',
    'ROUTE': '2호선',
    'LAT': '37.574747',
    'LOT': '127.024932'},
   {'BLDN_ID': '0247',
    'BLDN_NM': '도림천',
    'ROUTE': '2호선',
    'LAT': '37.514287',
    'LOT': '126.882768'},
   {'BLDN_ID': '0248',
    'BLDN_NM': '양천구청',
    'ROUTE': '2호선',
    'LAT': '37.512398',
    'LOT': '126.865819'},
   {'BLDN_ID': '0249',
    'BLDN_NM': '신정네거리',
    'ROUTE': '2호선',
    'LAT': '37.520074',
    'LOT': '126.852912'},
   {'BLDN_ID': '0250',
    'BLDN_NM': '용두(동대문구청)',
    'ROUTE': '2호선',
    'LAT': '37.574028',
    'LOT': '127.038091'},
   {'BLDN_ID': '0309',
    'BLDN_NM': '지축',
    'ROUTE': '3호선',
    'LAT': '37.648033',
    'LOT': '126.913917'},
   {'BLDN_ID': '0310',
    'BLDN_NM': '구파발',
    'ROUTE': '3호선',
    'LAT': '37.636763',
    'LOT': '126.918821'},
   {'BLDN_ID': '0311',
    'BLDN_NM': '연신내',
    'ROUTE': '3호선',
    'LAT': '37.619229',
    'LOT': '126.921038'},
   {'BLDN_ID': '0312',
    'BLDN_NM': '불광',
    'ROUTE': '3호선',
    'LAT': '37.610553',
    'LOT': '126.92982'},
   {'BLDN_ID': '0313',
    'BLDN_NM': '녹번',
    'ROUTE': '3호선',
    'LAT': '37.600927',
    'LOT': '126.935756'},
   {'BLDN_ID': '0314',
    'BLDN_NM': '홍제',
    'ROUTE': '3호선',
    'LAT': '37.589066',
    'LOT': '126.943736'},
   {'BLDN_ID': '0315',
    'BLDN_NM': '무악재',
    'ROUTE': '3호선',
    'LAT': '37.582299',
    'LOT': '126.950291'},
   {'BLDN_ID': '0316',
    'BLDN_NM': '독립문',
    'ROUTE': '3호선',
    'LAT': '37.574571',
    'LOT': '126.957748'},
   {'BLDN_ID': '0317',
    'BLDN_NM': '경복궁(정부서울청사)',
    'ROUTE': '3호선',
    'LAT': '37.575762',
    'LOT': '126.97353'},
   {'BLDN_ID': '0318',
    'BLDN_NM': '안국',
    'ROUTE': '3호선',
    'LAT': '37.576477',
    'LOT': '126.985443'},
   {'BLDN_ID': '0319',
    'BLDN_NM': '종로3가',
    'ROUTE': '3호선',
    'LAT': '37.571605',
    'LOT': '126.991791'},
   {'BLDN_ID': '0320',
    'BLDN_NM': '을지로3가',
    'ROUTE': '3호선',
    'LAT': '37.566672',
    'LOT': '126.992548'},
   {'BLDN_ID': '0321',
    'BLDN_NM': '충무로',
    'ROUTE': '3호선',
    'LAT': '37.56143',
    'LOT': '126.994072'},
   {'BLDN_ID': '0322',
    'BLDN_NM': '동대입구',
    'ROUTE': '3호선',
    'LAT': '37.559052',
    'LOT': '127.005602'},
   {'BLDN_ID': '0323',
    'BLDN_NM': '약수',
    'ROUTE': '3호선',
    'LAT': '37.554867',
    'LOT': '127.010541'},
   {'BLDN_ID': '0324',
    'BLDN_NM': '금호',
    'ROUTE': '3호선',
    'LAT': '37.548034',
    'LOT': '127.015872'},
   {'BLDN_ID': '0325',
    'BLDN_NM': '옥수',
    'ROUTE': '3호선',
    'LAT': '37.541684',
    'LOT': '127.017269'},
   {'BLDN_ID': '0326',
    'BLDN_NM': '압구정',
    'ROUTE': '3호선',
    'LAT': '37.527072',
    'LOT': '127.028461'},
   {'BLDN_ID': '0327',
    'BLDN_NM': '신사',
    'ROUTE': '3호선',
    'LAT': '37.516334',
    'LOT': '127.020114'},
   {'BLDN_ID': '0328',
    'BLDN_NM': '잠원',
    'ROUTE': '3호선',
    'LAT': '37.512759',
    'LOT': '127.01122'},
   {'BLDN_ID': '0329',
    'BLDN_NM': '고속터미널',
    'ROUTE': '3호선',
    'LAT': '37.504891',
    'LOT': '127.004916'},
   {'BLDN_ID': '0330',
    'BLDN_NM': '교대(법원.검찰청)',
    'ROUTE': '3호선',
    'LAT': '37.493025',
    'LOT': '127.013786'},
   {'BLDN_ID': '0331',
    'BLDN_NM': '남부터미널(예술의전당)',
    'ROUTE': '3호선',
    'LAT': '37.485013',
    'LOT': '127.016189'},
   {'BLDN_ID': '0332',
    'BLDN_NM': '양재(서초구청)',
    'ROUTE': '3호선',
    'LAT': '37.484477',
    'LOT': '127.033902'},
   {'BLDN_ID': '0333',
    'BLDN_NM': '매봉',
    'ROUTE': '3호선',
    'LAT': '37.486947',
    'LOT': '127.046769'},
   {'BLDN_ID': '0334',
    'BLDN_NM': '도곡',
    'ROUTE': '3호선',
    'LAT': '37.490922',
    'LOT': '127.055452'},
   {'BLDN_ID': '0335',
    'BLDN_NM': '대치',
    'ROUTE': '3호선',
    'LAT': '37.494612',
    'LOT': '127.063642'},
   {'BLDN_ID': '0336',
    'BLDN_NM': '학여울',
    'ROUTE': '3호선',
    'LAT': '37.496663',
    'LOT': '127.070594'},
   {'BLDN_ID': '0337',
    'BLDN_NM': '대청',
    'ROUTE': '3호선',
    'LAT': '37.493514',
    'LOT': '127.079532'},
   {'BLDN_ID': '0338',
    'BLDN_NM': '일원',
    'ROUTE': '3호선',
    'LAT': '37.483681',
    'LOT': '127.08439'},
   {'BLDN_ID': '0339',
    'BLDN_NM': '수서',
    'ROUTE': '3호선',
    'LAT': '37.487378',
    'LOT': '127.101907'},
   {'BLDN_ID': '0340',
    'BLDN_NM': '가락시장',
    'ROUTE': '3호선',
    'LAT': '37.492245',
    'LOT': '127.117757'},
   {'BLDN_ID': '0341',
    'BLDN_NM': '경찰병원',
    'ROUTE': '3호선',
    'LAT': '37.495918',
    'LOT': '127.12454'},
   {'BLDN_ID': '0342',
    'BLDN_NM': '오금',
    'ROUTE': '3호선',
    'LAT': '37.502129',
    'LOT': '127.128319'},
   {'BLDN_ID': '0405',
    'BLDN_NM': '진접',
    'ROUTE': '진접선',
    'LAT': '37.7205',
    'LOT': '127.2034'},
   {'BLDN_ID': '0406',
    'BLDN_NM': '오남',
    'ROUTE': '진접선',
    'LAT': '37.705',
    'LOT': '127.19281'},
   {'BLDN_ID': '0408',
    'BLDN_NM': '별내별가람',
    'ROUTE': '진접선',
    'LAT': '37.66778',
    'LOT': '127.11581'},
   {'BLDN_ID': '0409',
    'BLDN_NM': '당고개',
    'ROUTE': '4호선',
    'LAT': '37.670272',
    'LOT': '127.079066'},
   {'BLDN_ID': '0410',
    'BLDN_NM': '상계',
    'ROUTE': '4호선',
    'LAT': '37.660878',
    'LOT': '127.073572'},
   {'BLDN_ID': '0411',
    'BLDN_NM': '노원',
    'ROUTE': '4호선',
    'LAT': '37.65627',
    'LOT': '127.063276'},
   {'BLDN_ID': '0412',
    'BLDN_NM': '창동',
    'ROUTE': '4호선',
    'LAT': '37.653088',
    'LOT': '127.047274'},
   {'BLDN_ID': '0413',
    'BLDN_NM': '쌍문',
    'ROUTE': '4호선',
    'LAT': '37.648627',
    'LOT': '127.034709'},
   {'BLDN_ID': '0414',
    'BLDN_NM': '수유(강북구청)',
    'ROUTE': '4호선',
    'LAT': '37.638052',
    'LOT': '127.025732'},
   {'BLDN_ID': '0415',
    'BLDN_NM': '미아(서울사이버대학)',
    'ROUTE': '4호선',
    'LAT': '37.62667',
    'LOT': '127.025983'},
   {'BLDN_ID': '0416',
    'BLDN_NM': '미아사거리',
    'ROUTE': '4호선',
    'LAT': '37.613292',
    'LOT': '127.030053'},
   {'BLDN_ID': '0417',
    'BLDN_NM': '길음',
    'ROUTE': '4호선',
    'LAT': '37.603407',
    'LOT': '127.025053'},
   {'BLDN_ID': '0418',
    'BLDN_NM': '성신여대입구(돈암)',
    'ROUTE': '4호선',
    'LAT': '37.592612',
    'LOT': '127.016441'},
   {'BLDN_ID': '0419',
    'BLDN_NM': '한성대입구(삼선교)',
    'ROUTE': '4호선',
    'LAT': '37.588458',
    'LOT': '127.006221'},
   {'BLDN_ID': '0420',
    'BLDN_NM': '혜화',
    'ROUTE': '4호선',
    'LAT': '37.582336',
    'LOT': '127.001844'},
   {'BLDN_ID': '0421',
    'BLDN_NM': '동대문',
    'ROUTE': '4호선',
    'LAT': '37.57093',
    'LOT': '127.009287'},
   {'BLDN_ID': '0422',
    'BLDN_NM': '동대문역사문화공원',
    'ROUTE': '4호선',
    'LAT': '37.565133',
    'LOT': '127.007885'},
   {'BLDN_ID': '0423',
    'BLDN_NM': '충무로',
    'ROUTE': '4호선',
    'LAT': '37.561207',
    'LOT': '126.99408'},
   {'BLDN_ID': '0424',
    'BLDN_NM': '명동',
    'ROUTE': '4호선',
    'LAT': '37.560989',
    'LOT': '126.986325'},
   {'BLDN_ID': '0425',
    'BLDN_NM': '회현(남대문시장)',
    'ROUTE': '4호선',
    'LAT': '37.558514',
    'LOT': '126.978246'},
   {'BLDN_ID': '0426',
    'BLDN_NM': '서울역',
    'ROUTE': '4호선',
    'LAT': '37.55281',
    'LOT': '126.972556'},
   {'BLDN_ID': '0427',
    'BLDN_NM': '숙대입구(갈월)',
    'ROUTE': '4호선',
    'LAT': '37.54456',
    'LOT': '126.972106'},
   {'BLDN_ID': '0428',
    'BLDN_NM': '삼각지',
    'ROUTE': '4호선',
    'LAT': '37.534075',
    'LOT': '126.9726'},
   {'BLDN_ID': '0429',
    'BLDN_NM': '신용산',
    'ROUTE': '4호선',
    'LAT': '37.52917',
    'LOT': '126.967894'},
   {'BLDN_ID': '0430',
    'BLDN_NM': '이촌(국립중앙박물관)',
    'ROUTE': '4호선',
    'LAT': '37.522295',
    'LOT': '126.974733'},
   {'BLDN_ID': '0431',
    'BLDN_NM': '동작(현충원)',
    'ROUTE': '4호선',
    'LAT': '37.502852',
    'LOT': '126.980347'},
   {'BLDN_ID': '0432',
    'BLDN_NM': '총신대입구(이수)',
    'ROUTE': '4호선',
    'LAT': '37.486263',
    'LOT': '126.981989'},
   {'BLDN_ID': '0433',
    'BLDN_NM': '사당',
    'ROUTE': '4호선',
    'LAT': '37.476955',
    'LOT': '126.981651'},
   {'BLDN_ID': '0434',
    'BLDN_NM': '남태령',
    'ROUTE': '4호선',
    'LAT': '37.463873',
    'LOT': '126.989134'},
   {'BLDN_ID': '1001',
    'BLDN_NM': '서울역',
    'ROUTE': '경부선',
    'LAT': '37.554337',
    'LOT': '126.971134'},
   {'BLDN_ID': '1002',
    'BLDN_NM': '남영',
    'ROUTE': '경부선',
    'LAT': '37.541021',
    'LOT': '126.9713'},
   {'BLDN_ID': '1003',
    'BLDN_NM': '용산',
    'ROUTE': '경부선',
    'LAT': '37.529849',
    'LOT': '126.964561'},
   {'BLDN_ID': '1004',
    'BLDN_NM': '노량진',
    'ROUTE': '경부선',
    'LAT': '37.514149',
    'LOT': '126.94271'},
   {'BLDN_ID': '1005',
    'BLDN_NM': '대방',
    'ROUTE': '경부선',
    'LAT': '37.513342',
    'LOT': '126.926382'},
   {'BLDN_ID': '1006',
    'BLDN_NM': '영등포',
    'ROUTE': '경부선',
    'LAT': '37.515504',
    'LOT': '126.907628'},
   {'BLDN_ID': '1007',
    'BLDN_NM': '신도림',
    'ROUTE': '경부선',
    'LAT': '37.508787',
    'LOT': '126.891144'},
   {'BLDN_ID': '1008',
    'BLDN_NM': '이촌(국립중앙박물관)',
    'ROUTE': '경원선',
    'LAT': '37.522427',
    'LOT': '126.973406'},
   {'BLDN_ID': '1009',
    'BLDN_NM': '서빙고',
    'ROUTE': '경원선',
    'LAT': '37.519594',
    'LOT': '126.988537'},
   {'BLDN_ID': '1010',
    'BLDN_NM': '한남',
    'ROUTE': '경원선',
    'LAT': '37.52943',
    'LOT': '127.009169'},
   {'BLDN_ID': '1011',
    'BLDN_NM': '옥수',
    'ROUTE': '경원선',
    'LAT': '37.540446',
    'LOT': '127.018672'},
   {'BLDN_ID': '1012',
    'BLDN_NM': '응봉',
    'ROUTE': '경원선',
    'LAT': '37.549946',
    'LOT': '127.034538'},
   {'BLDN_ID': '1013',
    'BLDN_NM': '왕십리(성동구청)',
    'ROUTE': '경원선',
    'LAT': '37.561827',
    'LOT': '127.038352'},
   {'BLDN_ID': '1014',
    'BLDN_NM': '청량리(서울시립대입구)',
    'ROUTE': '경원선',
    'LAT': '37.580759',
    'LOT': '127.0483'},
   {'BLDN_ID': '1015',
    'BLDN_NM': '회기',
    'ROUTE': '중앙선',
    'LAT': '37.58946',
    'LOT': '127.057583'},
   {'BLDN_ID': '1016',
    'BLDN_NM': '외대앞',
    'ROUTE': '경원선',
    'LAT': '37.596073',
    'LOT': '127.063549'},
   {'BLDN_ID': '1017',
    'BLDN_NM': '신이문',
    'ROUTE': '경원선',
    'LAT': '37.601854',
    'LOT': '127.067325'},
   {'BLDN_ID': '1018',
    'BLDN_NM': '석계',
    'ROUTE': '경원선',
    'LAT': '37.614532',
    'LOT': '127.065934'},
   {'BLDN_ID': '1019',
    'BLDN_NM': '광운대',
    'ROUTE': '경원선',
    'LAT': '37.623632',
    'LOT': '127.061835'},
   {'BLDN_ID': '1020',
    'BLDN_NM': '월계',
    'ROUTE': '경원선',
    'LAT': '37.633212',
    'LOT': '127.058831'},
   {'BLDN_ID': '1021',
    'BLDN_NM': '녹천',
    'ROUTE': '경원선',
    'LAT': '37.644799',
    'LOT': '127.051269'},
   {'BLDN_ID': '1022',
    'BLDN_NM': '창동',
    'ROUTE': '경원선',
    'LAT': '37.653007',
    'LOT': '127.047806'},
   {'BLDN_ID': '1023',
    'BLDN_NM': '선릉',
    'ROUTE': '분당선',
    'LAT': '37.504856',
    'LOT': '127.048807'},
   {'BLDN_ID': '1024',
    'BLDN_NM': '한티',
    'ROUTE': '분당선',
    'LAT': '37.496237',
    'LOT': '127.052873'},
   {'BLDN_ID': '1025',
    'BLDN_NM': '도곡',
    'ROUTE': '분당선',
    'LAT': '37.491224',
    'LOT': '127.055186'},
   {'BLDN_ID': '1026',
    'BLDN_NM': '구룡',
    'ROUTE': '분당선',
    'LAT': '37.486839',
    'LOT': '127.058856'},
   {'BLDN_ID': '1027',
    'BLDN_NM': '개포동',
    'ROUTE': '분당선',
    'LAT': '37.489116',
    'LOT': '127.06614'},
   {'BLDN_ID': '1028',
    'BLDN_NM': '대모산입구',
    'ROUTE': '분당선',
    'LAT': '37.491373',
    'LOT': '127.07272'},
   {'BLDN_ID': '1030',
    'BLDN_NM': '수서',
    'ROUTE': '분당선',
    'LAT': '37.487472',
    'LOT': '127.101422'},
   {'BLDN_ID': '1031',
    'BLDN_NM': '복정',
    'ROUTE': '분당선',
    'LAT': '37.470345',
    'LOT': '127.126658'},
   {'BLDN_ID': '1032',
    'BLDN_NM': '신길',
    'ROUTE': '경부선',
    'LAT': '37.516862',
    'LOT': '126.917865'},
   {'BLDN_ID': '1201',
    'BLDN_NM': '중랑',
    'ROUTE': '중앙선',
    'LAT': '37.594917',
    'LOT': '127.076116'},
   {'BLDN_ID': '1202',
    'BLDN_NM': '상봉(시외버스터미널)',
    'ROUTE': '중앙선',
    'LAT': '37.596678',
    'LOT': '127.08504'},
   {'BLDN_ID': '1203',
    'BLDN_NM': '망우',
    'ROUTE': '중앙선',
    'LAT': '37.59955',
    'LOT': '127.091909'},
   {'BLDN_ID': '1204',
    'BLDN_NM': '양원',
    'ROUTE': '중앙선',
    'LAT': '37.606596',
    'LOT': '127.107906'},
   {'BLDN_ID': '1205',
    'BLDN_NM': '구리',
    'ROUTE': '중앙선',
    'LAT': '37.603392',
    'LOT': '127.143869'},
   {'BLDN_ID': '1206',
    'BLDN_NM': '도농',
    'ROUTE': '중앙선',
    'LAT': '37.608806',
    'LOT': '127.161153'},
   {'BLDN_ID': '1207',
    'BLDN_NM': '양정',
    'ROUTE': '중앙선',
    'LAT': '37.60533',
    'LOT': '127.19364'},
   {'BLDN_ID': '1208',
    'BLDN_NM': '덕소',
    'ROUTE': '중앙선',
    'LAT': '37.586781',
    'LOT': '127.208832'},
   {'BLDN_ID': '1209',
    'BLDN_NM': '도심',
    'ROUTE': '중앙선',
    'LAT': '37.579622',
    'LOT': '127.222672'},
   {'BLDN_ID': '1210',
    'BLDN_NM': '팔당',
    'ROUTE': '중앙선',
    'LAT': '37.547371',
    'LOT': '127.243939'},
   {'BLDN_ID': '1211',
    'BLDN_NM': '운길산',
    'ROUTE': '중앙선',
    'LAT': '37.554669',
    'LOT': '127.310115'},
   {'BLDN_ID': '1212',
    'BLDN_NM': '양수',
    'ROUTE': '중앙선',
    'LAT': '37.545981',
    'LOT': '127.329098'},
   {'BLDN_ID': '1213',
    'BLDN_NM': '신원',
    'ROUTE': '중앙선',
    'LAT': '37.525545',
    'LOT': '127.372921'},
   {'BLDN_ID': '1214',
    'BLDN_NM': '국수',
    'ROUTE': '중앙선',
    'LAT': '37.516169',
    'LOT': '127.399367'},
   {'BLDN_ID': '1215',
    'BLDN_NM': '아신',
    'ROUTE': '중앙선',
    'LAT': '37.51382',
    'LOT': '127.443173'},
   {'BLDN_ID': '1216',
    'BLDN_NM': '오빈',
    'ROUTE': '중앙선',
    'LAT': '37.506062',
    'LOT': '127.473868'},
   {'BLDN_ID': '1217',
    'BLDN_NM': '양평',
    'ROUTE': '중앙선',
    'LAT': '37.492773',
    'LOT': '127.491837'},
   {'BLDN_ID': '1218',
    'BLDN_NM': '원덕',
    'ROUTE': '중앙선',
    'LAT': '37.468672',
    'LOT': '127.547076'},

In [28]:
import pandas as pd
temp = []
for d in data['subwayStationMaster']['row']:
  temp.append(d)
uni = pd.DataFrame(temp)
uni.head()

  BLDN_ID BLDN_NM ROUTE        LAT         LOT
0    0150     서울역   1호선  37.556228  126.972135
1    0151      시청   1호선  37.565715  126.977088
2    0152      종각   1호선  37.570161  126.982923
3    0153    종로3가   1호선  37.570406  126.991847
4    0154    종로5가   1호선  37.570926  127.001849

In [30]:
import folium
anMap = folium.Map(location=[37.88988548,127.1371472],
                    zoom_control=False,
                    zoom_start=11,
                    control_scale= True)
anMap

In [31]:

from folium.plugins import MarkerCluster
mc = MarkerCluster().add_to(anMap)

for n, row in uni.iterrows():
  folium.Marker(location=[row['LAT'], row['LOT']], popup = folium.Popup(row['BLDN_NM'], max_width=200)).add_to(mc)

anMap

In [32]:
anMap.save('오픈API활용한folium맵표시.html')